//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/meshCollisionSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricMeshCollisionSchemaTokens,
    FABRIC_MESH_COLLISION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
FabricMeshCollisionSchema::GetApproximation() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        FabricMeshCollisionSchemaTokens->approximation);
}

/*static*/
HdContainerDataSourceHandle
FabricMeshCollisionSchema::BuildRetained(
        const HdTokenDataSourceHandle &approximation
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (approximation) {
        _names[_count] = FabricMeshCollisionSchemaTokens->approximation;
        _values[_count++] = approximation;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricMeshCollisionSchema::Builder &
FabricMeshCollisionSchema::Builder::SetApproximation(
    const HdTokenDataSourceHandle &approximation)
{
    _approximation = approximation;
    return *this;
}

HdContainerDataSourceHandle
FabricMeshCollisionSchema::Builder::Build()
{
    return FabricMeshCollisionSchema::BuildRetained(
        _approximation
    );
}

/*static*/
FabricMeshCollisionSchema
FabricMeshCollisionSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricMeshCollisionSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricMeshCollisionSchemaTokens->meshCollision))
        : nullptr);
}

/*static*/
const TfToken &
FabricMeshCollisionSchema::GetSchemaToken()
{
    return FabricMeshCollisionSchemaTokens->meshCollision;
}

/*static*/
const HdDataSourceLocator &
FabricMeshCollisionSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricMeshCollisionSchema::GetApproximationLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricMeshCollisionSchemaTokens->approximation);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE