//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_FABRIC_PHYSX_VEHICLE_NONLINEAR_COMMAND_RESPONSE_SCHEMA_H
#define PXR_IMAGING_FABRIC_PHYSX_VEHICLE_NONLINEAR_COMMAND_RESPONSE_SCHEMA_H

/// \file

#include "pxr/imaging/fabric/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define FABRIC_PHYSX_VEHICLE_NONLINEAR_COMMAND_RESPONSE_SCHEMA_TOKENS \
    (physxVehicleNonlinearCommandResponse) \
    (commandValues) \
    (speedResponses) \
    (speedResponsesPerCommandValue) \

TF_DECLARE_PUBLIC_TOKENS(FabricPhysxVehicleNonlinearCommandResponseSchemaTokens, FABRIC_API,
    FABRIC_PHYSX_VEHICLE_NONLINEAR_COMMAND_RESPONSE_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class FabricPhysxVehicleNonlinearCommandResponseSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    FabricPhysxVehicleNonlinearCommandResponseSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxVehicleNonlinearCommandResponse" from the parent container and constructs a
    /// FabricPhysxVehicleNonlinearCommandResponseSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    FABRIC_API
    static FabricPhysxVehicleNonlinearCommandResponseSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    FABRIC_API
    HdFloatArrayDataSourceHandle GetCommandValues() const;

    FABRIC_API
    HdVec2fArrayDataSourceHandle GetSpeedResponses() const;

    FABRIC_API
    HdIntArrayDataSourceHandle GetSpeedResponsesPerCommandValue() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    FABRIC_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    FABRIC_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate commandValues.
    FABRIC_API
    static const HdDataSourceLocator &GetCommandValuesLocator();

    /// Prim-level relative data source locator to locate speedResponses.
    FABRIC_API
    static const HdDataSourceLocator &GetSpeedResponsesLocator();

    /// Prim-level relative data source locator to locate speedResponsesPerCommandValue.
    FABRIC_API
    static const HdDataSourceLocator &GetSpeedResponsesPerCommandValueLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    FABRIC_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdFloatArrayDataSourceHandle &commandValues,
        const HdVec2fArrayDataSourceHandle &speedResponses,
        const HdIntArrayDataSourceHandle &speedResponsesPerCommandValue
    );

    /// \class FabricPhysxVehicleNonlinearCommandResponseSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        FABRIC_API
        Builder &SetCommandValues(
            const HdFloatArrayDataSourceHandle &commandValues);
        FABRIC_API
        Builder &SetSpeedResponses(
            const HdVec2fArrayDataSourceHandle &speedResponses);
        FABRIC_API
        Builder &SetSpeedResponsesPerCommandValue(
            const HdIntArrayDataSourceHandle &speedResponsesPerCommandValue);

        /// Returns a container data source containing the members set thus far.
        FABRIC_API
        HdContainerDataSourceHandle Build();

    private:
        HdFloatArrayDataSourceHandle _commandValues;
        HdVec2fArrayDataSourceHandle _speedResponses;
        HdIntArrayDataSourceHandle _speedResponsesPerCommandValue;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif