//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxVehicleTireFrictionTableSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxVehicleTireFrictionTableSchemaTokens,
    FABRIC_PHYSX_VEHICLE_TIRE_FRICTION_TABLE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
FabricPhysxVehicleTireFrictionTableSchema::GetDefaultFrictionValue() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue);
}

HdFloatArrayDataSourceHandle
FabricPhysxVehicleTireFrictionTableSchema::GetFrictionValues() const
{
    return _GetTypedDataSource<HdFloatArrayDataSource>(
        FabricPhysxVehicleTireFrictionTableSchemaTokens->frictionValues);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxVehicleTireFrictionTableSchema::BuildRetained(
        const HdFloatDataSourceHandle &defaultFrictionValue,
        const HdFloatArrayDataSourceHandle &frictionValues
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (defaultFrictionValue) {
        _names[_count] = FabricPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue;
        _values[_count++] = defaultFrictionValue;
    }

    if (frictionValues) {
        _names[_count] = FabricPhysxVehicleTireFrictionTableSchemaTokens->frictionValues;
        _values[_count++] = frictionValues;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxVehicleTireFrictionTableSchema::Builder &
FabricPhysxVehicleTireFrictionTableSchema::Builder::SetDefaultFrictionValue(
    const HdFloatDataSourceHandle &defaultFrictionValue)
{
    _defaultFrictionValue = defaultFrictionValue;
    return *this;
}

FabricPhysxVehicleTireFrictionTableSchema::Builder &
FabricPhysxVehicleTireFrictionTableSchema::Builder::SetFrictionValues(
    const HdFloatArrayDataSourceHandle &frictionValues)
{
    _frictionValues = frictionValues;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxVehicleTireFrictionTableSchema::Builder::Build()
{
    return FabricPhysxVehicleTireFrictionTableSchema::BuildRetained(
        _defaultFrictionValue,
        _frictionValues
    );
}

/*static*/
FabricPhysxVehicleTireFrictionTableSchema
FabricPhysxVehicleTireFrictionTableSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxVehicleTireFrictionTableSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxVehicleTireFrictionTableSchemaTokens->physxVehicleTireFrictionTable))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxVehicleTireFrictionTableSchema::GetSchemaToken()
{
    return FabricPhysxVehicleTireFrictionTableSchemaTokens->physxVehicleTireFrictionTable;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxVehicleTireFrictionTableSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireFrictionTableSchema::GetDefaultFrictionValueLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireFrictionTableSchema::GetFrictionValuesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireFrictionTableSchemaTokens->frictionValues);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE