//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxTriangleMeshCollisionSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxTriangleMeshCollisionSchemaTokens,
    FABRIC_PHYSX_TRIANGLE_MESH_COLLISION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
FabricPhysxTriangleMeshCollisionSchema::GetWeldTolerance() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxTriangleMeshCollisionSchemaTokens->weldTolerance);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxTriangleMeshCollisionSchema::BuildRetained(
        const HdFloatDataSourceHandle &weldTolerance
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (weldTolerance) {
        _names[_count] = FabricPhysxTriangleMeshCollisionSchemaTokens->weldTolerance;
        _values[_count++] = weldTolerance;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxTriangleMeshCollisionSchema::Builder &
FabricPhysxTriangleMeshCollisionSchema::Builder::SetWeldTolerance(
    const HdFloatDataSourceHandle &weldTolerance)
{
    _weldTolerance = weldTolerance;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxTriangleMeshCollisionSchema::Builder::Build()
{
    return FabricPhysxTriangleMeshCollisionSchema::BuildRetained(
        _weldTolerance
    );
}

/*static*/
FabricPhysxTriangleMeshCollisionSchema
FabricPhysxTriangleMeshCollisionSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxTriangleMeshCollisionSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxTriangleMeshCollisionSchemaTokens->physxTriangleMeshCollision))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxTriangleMeshCollisionSchema::GetSchemaToken()
{
    return FabricPhysxTriangleMeshCollisionSchemaTokens->physxTriangleMeshCollision;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxTriangleMeshCollisionSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxTriangleMeshCollisionSchema::GetWeldToleranceLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxTriangleMeshCollisionSchemaTokens->weldTolerance);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE