//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxMaterialSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxMaterialSchemaTokens,
    FABRIC_PHYSX_MATERIAL_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdBoolDataSourceHandle
FabricPhysxMaterialSchema::GetCompliantContactAccelerationSpring() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        FabricPhysxMaterialSchemaTokens->compliantContactAccelerationSpring);
}

HdFloatDataSourceHandle
FabricPhysxMaterialSchema::GetCompliantContactDamping() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxMaterialSchemaTokens->compliantContactDamping);
}

HdFloatDataSourceHandle
FabricPhysxMaterialSchema::GetCompliantContactStiffness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxMaterialSchemaTokens->compliantContactStiffness);
}

HdTokenDataSourceHandle
FabricPhysxMaterialSchema::GetDampingCombineMode() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        FabricPhysxMaterialSchemaTokens->dampingCombineMode);
}

HdTokenDataSourceHandle
FabricPhysxMaterialSchema::GetFrictionCombineMode() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        FabricPhysxMaterialSchemaTokens->frictionCombineMode);
}

HdTokenDataSourceHandle
FabricPhysxMaterialSchema::GetRestitutionCombineMode() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        FabricPhysxMaterialSchemaTokens->restitutionCombineMode);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxMaterialSchema::BuildRetained(
        const HdBoolDataSourceHandle &compliantContactAccelerationSpring,
        const HdFloatDataSourceHandle &compliantContactDamping,
        const HdFloatDataSourceHandle &compliantContactStiffness,
        const HdTokenDataSourceHandle &dampingCombineMode,
        const HdTokenDataSourceHandle &frictionCombineMode,
        const HdTokenDataSourceHandle &restitutionCombineMode
)
{
    TfToken _names[6];
    HdDataSourceBaseHandle _values[6];

    size_t _count = 0;

    if (compliantContactAccelerationSpring) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->compliantContactAccelerationSpring;
        _values[_count++] = compliantContactAccelerationSpring;
    }

    if (compliantContactDamping) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->compliantContactDamping;
        _values[_count++] = compliantContactDamping;
    }

    if (compliantContactStiffness) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->compliantContactStiffness;
        _values[_count++] = compliantContactStiffness;
    }

    if (dampingCombineMode) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->dampingCombineMode;
        _values[_count++] = dampingCombineMode;
    }

    if (frictionCombineMode) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->frictionCombineMode;
        _values[_count++] = frictionCombineMode;
    }

    if (restitutionCombineMode) {
        _names[_count] = FabricPhysxMaterialSchemaTokens->restitutionCombineMode;
        _values[_count++] = restitutionCombineMode;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetCompliantContactAccelerationSpring(
    const HdBoolDataSourceHandle &compliantContactAccelerationSpring)
{
    _compliantContactAccelerationSpring = compliantContactAccelerationSpring;
    return *this;
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetCompliantContactDamping(
    const HdFloatDataSourceHandle &compliantContactDamping)
{
    _compliantContactDamping = compliantContactDamping;
    return *this;
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetCompliantContactStiffness(
    const HdFloatDataSourceHandle &compliantContactStiffness)
{
    _compliantContactStiffness = compliantContactStiffness;
    return *this;
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetDampingCombineMode(
    const HdTokenDataSourceHandle &dampingCombineMode)
{
    _dampingCombineMode = dampingCombineMode;
    return *this;
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetFrictionCombineMode(
    const HdTokenDataSourceHandle &frictionCombineMode)
{
    _frictionCombineMode = frictionCombineMode;
    return *this;
}

FabricPhysxMaterialSchema::Builder &
FabricPhysxMaterialSchema::Builder::SetRestitutionCombineMode(
    const HdTokenDataSourceHandle &restitutionCombineMode)
{
    _restitutionCombineMode = restitutionCombineMode;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxMaterialSchema::Builder::Build()
{
    return FabricPhysxMaterialSchema::BuildRetained(
        _compliantContactAccelerationSpring,
        _compliantContactDamping,
        _compliantContactStiffness,
        _dampingCombineMode,
        _frictionCombineMode,
        _restitutionCombineMode
    );
}

/*static*/
FabricPhysxMaterialSchema
FabricPhysxMaterialSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxMaterialSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxMaterialSchemaTokens->physxMaterial))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxMaterialSchema::GetSchemaToken()
{
    return FabricPhysxMaterialSchemaTokens->physxMaterial;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetCompliantContactAccelerationSpringLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->compliantContactAccelerationSpring);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetCompliantContactDampingLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->compliantContactDamping);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetCompliantContactStiffnessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->compliantContactStiffness);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetDampingCombineModeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->dampingCombineMode);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetFrictionCombineModeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->frictionCombineMode);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxMaterialSchema::GetRestitutionCombineModeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxMaterialSchemaTokens->restitutionCombineMode);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE