//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_FABRIC_PHYSX_ISOSURFACE_SCHEMA_H
#define PXR_IMAGING_FABRIC_PHYSX_ISOSURFACE_SCHEMA_H

/// \file

#include "pxr/imaging/fabric/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define FABRIC_PHYSX_ISOSURFACE_SCHEMA_TOKENS \
    (physxIsosurface) \
    (anisotropyMax) \
    (anisotropyMin) \
    (anisotropyRadius) \
    (enableAnisotropy) \
    (gridFilteringPasses) \
    (gridSmoothingRadiusRelativeToCellSize) \
    (gridSpacing) \
    (isoSurfaceEnabled) \
    (isosurfaceLevel) \
    (kernelRadius) \
    (maxSubgrids) \
    (maxTriangles) \
    (maxVertices) \
    (numMeshSmoothingPasses) \

TF_DECLARE_PUBLIC_TOKENS(FabricPhysxIsosurfaceSchemaTokens, FABRIC_API,
    FABRIC_PHYSX_ISOSURFACE_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class FabricPhysxIsosurfaceSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    FabricPhysxIsosurfaceSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxIsosurface" from the parent container and constructs a
    /// FabricPhysxIsosurfaceSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    FABRIC_API
    static FabricPhysxIsosurfaceSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    FABRIC_API
    HdFloatDataSourceHandle GetAnisotropyMax() const;

    FABRIC_API
    HdFloatDataSourceHandle GetAnisotropyMin() const;

    FABRIC_API
    HdFloatDataSourceHandle GetAnisotropyRadius() const;

    FABRIC_API
    HdBoolDataSourceHandle GetEnableAnisotropy() const;

    FABRIC_API
    HdStringDataSourceHandle GetGridFilteringPasses() const;

    FABRIC_API
    HdFloatDataSourceHandle GetGridSmoothingRadiusRelativeToCellSize() const;

    FABRIC_API
    HdFloatDataSourceHandle GetGridSpacing() const;

    FABRIC_API
    HdBoolDataSourceHandle GetIsoSurfaceEnabled() const;

    FABRIC_API
    HdFloatDataSourceHandle GetIsosurfaceLevel() const;

    FABRIC_API
    HdFloatDataSourceHandle GetKernelRadius() const;

    FABRIC_API
    HdIntDataSourceHandle GetMaxSubgrids() const;

    FABRIC_API
    HdIntDataSourceHandle GetMaxTriangles() const;

    FABRIC_API
    HdIntDataSourceHandle GetMaxVertices() const;

    FABRIC_API
    HdIntDataSourceHandle GetNumMeshSmoothingPasses() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    FABRIC_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    FABRIC_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate anisotropyMax.
    FABRIC_API
    static const HdDataSourceLocator &GetAnisotropyMaxLocator();

    /// Prim-level relative data source locator to locate anisotropyMin.
    FABRIC_API
    static const HdDataSourceLocator &GetAnisotropyMinLocator();

    /// Prim-level relative data source locator to locate anisotropyRadius.
    FABRIC_API
    static const HdDataSourceLocator &GetAnisotropyRadiusLocator();

    /// Prim-level relative data source locator to locate enableAnisotropy.
    FABRIC_API
    static const HdDataSourceLocator &GetEnableAnisotropyLocator();

    /// Prim-level relative data source locator to locate gridFilteringPasses.
    FABRIC_API
    static const HdDataSourceLocator &GetGridFilteringPassesLocator();

    /// Prim-level relative data source locator to locate gridSmoothingRadiusRelativeToCellSize.
    FABRIC_API
    static const HdDataSourceLocator &GetGridSmoothingRadiusRelativeToCellSizeLocator();

    /// Prim-level relative data source locator to locate gridSpacing.
    FABRIC_API
    static const HdDataSourceLocator &GetGridSpacingLocator();

    /// Prim-level relative data source locator to locate isoSurfaceEnabled.
    FABRIC_API
    static const HdDataSourceLocator &GetIsoSurfaceEnabledLocator();

    /// Prim-level relative data source locator to locate isosurfaceLevel.
    FABRIC_API
    static const HdDataSourceLocator &GetIsosurfaceLevelLocator();

    /// Prim-level relative data source locator to locate kernelRadius.
    FABRIC_API
    static const HdDataSourceLocator &GetKernelRadiusLocator();

    /// Prim-level relative data source locator to locate maxSubgrids.
    FABRIC_API
    static const HdDataSourceLocator &GetMaxSubgridsLocator();

    /// Prim-level relative data source locator to locate maxTriangles.
    FABRIC_API
    static const HdDataSourceLocator &GetMaxTrianglesLocator();

    /// Prim-level relative data source locator to locate maxVertices.
    FABRIC_API
    static const HdDataSourceLocator &GetMaxVerticesLocator();

    /// Prim-level relative data source locator to locate numMeshSmoothingPasses.
    FABRIC_API
    static const HdDataSourceLocator &GetNumMeshSmoothingPassesLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    FABRIC_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdFloatDataSourceHandle &anisotropyMax,
        const HdFloatDataSourceHandle &anisotropyMin,
        const HdFloatDataSourceHandle &anisotropyRadius,
        const HdBoolDataSourceHandle &enableAnisotropy,
        const HdStringDataSourceHandle &gridFilteringPasses,
        const HdFloatDataSourceHandle &gridSmoothingRadiusRelativeToCellSize,
        const HdFloatDataSourceHandle &gridSpacing,
        const HdBoolDataSourceHandle &isoSurfaceEnabled,
        const HdFloatDataSourceHandle &isosurfaceLevel,
        const HdFloatDataSourceHandle &kernelRadius,
        const HdIntDataSourceHandle &maxSubgrids,
        const HdIntDataSourceHandle &maxTriangles,
        const HdIntDataSourceHandle &maxVertices,
        const HdIntDataSourceHandle &numMeshSmoothingPasses
    );

    /// \class FabricPhysxIsosurfaceSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        FABRIC_API
        Builder &SetAnisotropyMax(
            const HdFloatDataSourceHandle &anisotropyMax);
        FABRIC_API
        Builder &SetAnisotropyMin(
            const HdFloatDataSourceHandle &anisotropyMin);
        FABRIC_API
        Builder &SetAnisotropyRadius(
            const HdFloatDataSourceHandle &anisotropyRadius);
        FABRIC_API
        Builder &SetEnableAnisotropy(
            const HdBoolDataSourceHandle &enableAnisotropy);
        FABRIC_API
        Builder &SetGridFilteringPasses(
            const HdStringDataSourceHandle &gridFilteringPasses);
        FABRIC_API
        Builder &SetGridSmoothingRadiusRelativeToCellSize(
            const HdFloatDataSourceHandle &gridSmoothingRadiusRelativeToCellSize);
        FABRIC_API
        Builder &SetGridSpacing(
            const HdFloatDataSourceHandle &gridSpacing);
        FABRIC_API
        Builder &SetIsoSurfaceEnabled(
            const HdBoolDataSourceHandle &isoSurfaceEnabled);
        FABRIC_API
        Builder &SetIsosurfaceLevel(
            const HdFloatDataSourceHandle &isosurfaceLevel);
        FABRIC_API
        Builder &SetKernelRadius(
            const HdFloatDataSourceHandle &kernelRadius);
        FABRIC_API
        Builder &SetMaxSubgrids(
            const HdIntDataSourceHandle &maxSubgrids);
        FABRIC_API
        Builder &SetMaxTriangles(
            const HdIntDataSourceHandle &maxTriangles);
        FABRIC_API
        Builder &SetMaxVertices(
            const HdIntDataSourceHandle &maxVertices);
        FABRIC_API
        Builder &SetNumMeshSmoothingPasses(
            const HdIntDataSourceHandle &numMeshSmoothingPasses);

        /// Returns a container data source containing the members set thus far.
        FABRIC_API
        HdContainerDataSourceHandle Build();

    private:
        HdFloatDataSourceHandle _anisotropyMax;
        HdFloatDataSourceHandle _anisotropyMin;
        HdFloatDataSourceHandle _anisotropyRadius;
        HdBoolDataSourceHandle _enableAnisotropy;
        HdStringDataSourceHandle _gridFilteringPasses;
        HdFloatDataSourceHandle _gridSmoothingRadiusRelativeToCellSize;
        HdFloatDataSourceHandle _gridSpacing;
        HdBoolDataSourceHandle _isoSurfaceEnabled;
        HdFloatDataSourceHandle _isosurfaceLevel;
        HdFloatDataSourceHandle _kernelRadius;
        HdIntDataSourceHandle _maxSubgrids;
        HdIntDataSourceHandle _maxTriangles;
        HdIntDataSourceHandle _maxVertices;
        HdIntDataSourceHandle _numMeshSmoothingPasses;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif