//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxVehicleSteeringSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxVehicleSteeringSchemaTokens,
    FABRIC_PHYSX_VEHICLE_STEERING_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatArrayDataSourceHandle
FabricPhysxVehicleSteeringSchema::GetAngleMultipliers() const
{
    return _GetTypedDataSource<HdFloatArrayDataSource>(
        FabricPhysxVehicleSteeringSchemaTokens->angleMultipliers);
}

HdFloatDataSourceHandle
FabricPhysxVehicleSteeringSchema::GetMaxSteerAngle() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxVehicleSteeringSchemaTokens->maxSteerAngle);
}

HdIntArrayDataSourceHandle
FabricPhysxVehicleSteeringSchema::GetWheels() const
{
    return _GetTypedDataSource<HdIntArrayDataSource>(
        FabricPhysxVehicleSteeringSchemaTokens->wheels);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxVehicleSteeringSchema::BuildRetained(
        const HdFloatArrayDataSourceHandle &angleMultipliers,
        const HdFloatDataSourceHandle &maxSteerAngle,
        const HdIntArrayDataSourceHandle &wheels
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (angleMultipliers) {
        _names[_count] = FabricPhysxVehicleSteeringSchemaTokens->angleMultipliers;
        _values[_count++] = angleMultipliers;
    }

    if (maxSteerAngle) {
        _names[_count] = FabricPhysxVehicleSteeringSchemaTokens->maxSteerAngle;
        _values[_count++] = maxSteerAngle;
    }

    if (wheels) {
        _names[_count] = FabricPhysxVehicleSteeringSchemaTokens->wheels;
        _values[_count++] = wheels;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxVehicleSteeringSchema::Builder &
FabricPhysxVehicleSteeringSchema::Builder::SetAngleMultipliers(
    const HdFloatArrayDataSourceHandle &angleMultipliers)
{
    _angleMultipliers = angleMultipliers;
    return *this;
}

FabricPhysxVehicleSteeringSchema::Builder &
FabricPhysxVehicleSteeringSchema::Builder::SetMaxSteerAngle(
    const HdFloatDataSourceHandle &maxSteerAngle)
{
    _maxSteerAngle = maxSteerAngle;
    return *this;
}

FabricPhysxVehicleSteeringSchema::Builder &
FabricPhysxVehicleSteeringSchema::Builder::SetWheels(
    const HdIntArrayDataSourceHandle &wheels)
{
    _wheels = wheels;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxVehicleSteeringSchema::Builder::Build()
{
    return FabricPhysxVehicleSteeringSchema::BuildRetained(
        _angleMultipliers,
        _maxSteerAngle,
        _wheels
    );
}

/*static*/
FabricPhysxVehicleSteeringSchema
FabricPhysxVehicleSteeringSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxVehicleSteeringSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxVehicleSteeringSchemaTokens->physxVehicleSteering))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxVehicleSteeringSchema::GetSchemaToken()
{
    return FabricPhysxVehicleSteeringSchemaTokens->physxVehicleSteering;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxVehicleSteeringSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleSteeringSchema::GetAngleMultipliersLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleSteeringSchemaTokens->angleMultipliers);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleSteeringSchema::GetMaxSteerAngleLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleSteeringSchemaTokens->maxSteerAngle);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleSteeringSchema::GetWheelsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleSteeringSchemaTokens->wheels);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE