//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_FABRIC_PHYSX_COLLISION_SCHEMA_H
#define PXR_IMAGING_FABRIC_PHYSX_COLLISION_SCHEMA_H

/// \file

#include "pxr/imaging/fabric/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define FABRIC_PHYSX_COLLISION_SCHEMA_TOKENS \
    (physxCollision) \
    (contactOffset) \
    (minTorsionalPatchRadius) \
    (restOffset) \
    (torsionalPatchRadius) \

TF_DECLARE_PUBLIC_TOKENS(FabricPhysxCollisionSchemaTokens, FABRIC_API,
    FABRIC_PHYSX_COLLISION_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class FabricPhysxCollisionSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    FabricPhysxCollisionSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxCollision" from the parent container and constructs a
    /// FabricPhysxCollisionSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    FABRIC_API
    static FabricPhysxCollisionSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    FABRIC_API
    HdFloatDataSourceHandle GetContactOffset() const;

    FABRIC_API
    HdFloatDataSourceHandle GetMinTorsionalPatchRadius() const;

    FABRIC_API
    HdFloatDataSourceHandle GetRestOffset() const;

    FABRIC_API
    HdFloatDataSourceHandle GetTorsionalPatchRadius() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    FABRIC_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    FABRIC_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate contactOffset.
    FABRIC_API
    static const HdDataSourceLocator &GetContactOffsetLocator();

    /// Prim-level relative data source locator to locate minTorsionalPatchRadius.
    FABRIC_API
    static const HdDataSourceLocator &GetMinTorsionalPatchRadiusLocator();

    /// Prim-level relative data source locator to locate restOffset.
    FABRIC_API
    static const HdDataSourceLocator &GetRestOffsetLocator();

    /// Prim-level relative data source locator to locate torsionalPatchRadius.
    FABRIC_API
    static const HdDataSourceLocator &GetTorsionalPatchRadiusLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    FABRIC_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdFloatDataSourceHandle &contactOffset,
        const HdFloatDataSourceHandle &minTorsionalPatchRadius,
        const HdFloatDataSourceHandle &restOffset,
        const HdFloatDataSourceHandle &torsionalPatchRadius
    );

    /// \class FabricPhysxCollisionSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        FABRIC_API
        Builder &SetContactOffset(
            const HdFloatDataSourceHandle &contactOffset);
        FABRIC_API
        Builder &SetMinTorsionalPatchRadius(
            const HdFloatDataSourceHandle &minTorsionalPatchRadius);
        FABRIC_API
        Builder &SetRestOffset(
            const HdFloatDataSourceHandle &restOffset);
        FABRIC_API
        Builder &SetTorsionalPatchRadius(
            const HdFloatDataSourceHandle &torsionalPatchRadius);

        /// Returns a container data source containing the members set thus far.
        FABRIC_API
        HdContainerDataSourceHandle Build();

    private:
        HdFloatDataSourceHandle _contactOffset;
        HdFloatDataSourceHandle _minTorsionalPatchRadius;
        HdFloatDataSourceHandle _restOffset;
        HdFloatDataSourceHandle _torsionalPatchRadius;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif