//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxVehicleTireSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxVehicleTireSchemaTokens,
    FABRIC_PHYSX_VEHICLE_TIRE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
FabricPhysxVehicleTireSchema::GetCamberStiffness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxVehicleTireSchemaTokens->camberStiffness);
}

HdVec2fArrayDataSourceHandle
FabricPhysxVehicleTireSchema::GetFrictionVsSlipGraph() const
{
    return _GetTypedDataSource<HdVec2fArrayDataSource>(
        FabricPhysxVehicleTireSchemaTokens->frictionVsSlipGraph);
}

HdVec2fDataSourceHandle
FabricPhysxVehicleTireSchema::GetLateralStiffnessGraph() const
{
    return _GetTypedDataSource<HdVec2fDataSource>(
        FabricPhysxVehicleTireSchemaTokens->lateralStiffnessGraph);
}

HdFloatDataSourceHandle
FabricPhysxVehicleTireSchema::GetLongitudinalStiffness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxVehicleTireSchemaTokens->longitudinalStiffness);
}

HdFloatDataSourceHandle
FabricPhysxVehicleTireSchema::GetRestLoad() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricPhysxVehicleTireSchemaTokens->restLoad);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxVehicleTireSchema::BuildRetained(
        const HdFloatDataSourceHandle &camberStiffness,
        const HdVec2fArrayDataSourceHandle &frictionVsSlipGraph,
        const HdVec2fDataSourceHandle &lateralStiffnessGraph,
        const HdFloatDataSourceHandle &longitudinalStiffness,
        const HdFloatDataSourceHandle &restLoad
)
{
    TfToken _names[5];
    HdDataSourceBaseHandle _values[5];

    size_t _count = 0;

    if (camberStiffness) {
        _names[_count] = FabricPhysxVehicleTireSchemaTokens->camberStiffness;
        _values[_count++] = camberStiffness;
    }

    if (frictionVsSlipGraph) {
        _names[_count] = FabricPhysxVehicleTireSchemaTokens->frictionVsSlipGraph;
        _values[_count++] = frictionVsSlipGraph;
    }

    if (lateralStiffnessGraph) {
        _names[_count] = FabricPhysxVehicleTireSchemaTokens->lateralStiffnessGraph;
        _values[_count++] = lateralStiffnessGraph;
    }

    if (longitudinalStiffness) {
        _names[_count] = FabricPhysxVehicleTireSchemaTokens->longitudinalStiffness;
        _values[_count++] = longitudinalStiffness;
    }

    if (restLoad) {
        _names[_count] = FabricPhysxVehicleTireSchemaTokens->restLoad;
        _values[_count++] = restLoad;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxVehicleTireSchema::Builder &
FabricPhysxVehicleTireSchema::Builder::SetCamberStiffness(
    const HdFloatDataSourceHandle &camberStiffness)
{
    _camberStiffness = camberStiffness;
    return *this;
}

FabricPhysxVehicleTireSchema::Builder &
FabricPhysxVehicleTireSchema::Builder::SetFrictionVsSlipGraph(
    const HdVec2fArrayDataSourceHandle &frictionVsSlipGraph)
{
    _frictionVsSlipGraph = frictionVsSlipGraph;
    return *this;
}

FabricPhysxVehicleTireSchema::Builder &
FabricPhysxVehicleTireSchema::Builder::SetLateralStiffnessGraph(
    const HdVec2fDataSourceHandle &lateralStiffnessGraph)
{
    _lateralStiffnessGraph = lateralStiffnessGraph;
    return *this;
}

FabricPhysxVehicleTireSchema::Builder &
FabricPhysxVehicleTireSchema::Builder::SetLongitudinalStiffness(
    const HdFloatDataSourceHandle &longitudinalStiffness)
{
    _longitudinalStiffness = longitudinalStiffness;
    return *this;
}

FabricPhysxVehicleTireSchema::Builder &
FabricPhysxVehicleTireSchema::Builder::SetRestLoad(
    const HdFloatDataSourceHandle &restLoad)
{
    _restLoad = restLoad;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxVehicleTireSchema::Builder::Build()
{
    return FabricPhysxVehicleTireSchema::BuildRetained(
        _camberStiffness,
        _frictionVsSlipGraph,
        _lateralStiffnessGraph,
        _longitudinalStiffness,
        _restLoad
    );
}

/*static*/
FabricPhysxVehicleTireSchema
FabricPhysxVehicleTireSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxVehicleTireSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxVehicleTireSchemaTokens->physxVehicleTire))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxVehicleTireSchema::GetSchemaToken()
{
    return FabricPhysxVehicleTireSchemaTokens->physxVehicleTire;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetCamberStiffnessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireSchemaTokens->camberStiffness);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetFrictionVsSlipGraphLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireSchemaTokens->frictionVsSlipGraph);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetLateralStiffnessGraphLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireSchemaTokens->lateralStiffnessGraph);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetLongitudinalStiffnessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireSchemaTokens->longitudinalStiffness);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxVehicleTireSchema::GetRestLoadLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxVehicleTireSchemaTokens->restLoad);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE