//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/physxSurfaceVelocitySchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricPhysxSurfaceVelocitySchemaTokens,
    FABRIC_PHYSX_SURFACE_VELOCITY_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdVec3fDataSourceHandle
FabricPhysxSurfaceVelocitySchema::GetSurfaceAngularVelocity() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        FabricPhysxSurfaceVelocitySchemaTokens->surfaceAngularVelocity);
}

HdVec3fDataSourceHandle
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocity() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocity);
}

HdBoolDataSourceHandle
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocityEnabled() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityEnabled);
}

HdBoolDataSourceHandle
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocityLocalSpace() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityLocalSpace);
}

/*static*/
HdContainerDataSourceHandle
FabricPhysxSurfaceVelocitySchema::BuildRetained(
        const HdVec3fDataSourceHandle &surfaceAngularVelocity,
        const HdVec3fDataSourceHandle &surfaceVelocity,
        const HdBoolDataSourceHandle &surfaceVelocityEnabled,
        const HdBoolDataSourceHandle &surfaceVelocityLocalSpace
)
{
    TfToken _names[4];
    HdDataSourceBaseHandle _values[4];

    size_t _count = 0;

    if (surfaceAngularVelocity) {
        _names[_count] = FabricPhysxSurfaceVelocitySchemaTokens->surfaceAngularVelocity;
        _values[_count++] = surfaceAngularVelocity;
    }

    if (surfaceVelocity) {
        _names[_count] = FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocity;
        _values[_count++] = surfaceVelocity;
    }

    if (surfaceVelocityEnabled) {
        _names[_count] = FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityEnabled;
        _values[_count++] = surfaceVelocityEnabled;
    }

    if (surfaceVelocityLocalSpace) {
        _names[_count] = FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityLocalSpace;
        _values[_count++] = surfaceVelocityLocalSpace;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricPhysxSurfaceVelocitySchema::Builder &
FabricPhysxSurfaceVelocitySchema::Builder::SetSurfaceAngularVelocity(
    const HdVec3fDataSourceHandle &surfaceAngularVelocity)
{
    _surfaceAngularVelocity = surfaceAngularVelocity;
    return *this;
}

FabricPhysxSurfaceVelocitySchema::Builder &
FabricPhysxSurfaceVelocitySchema::Builder::SetSurfaceVelocity(
    const HdVec3fDataSourceHandle &surfaceVelocity)
{
    _surfaceVelocity = surfaceVelocity;
    return *this;
}

FabricPhysxSurfaceVelocitySchema::Builder &
FabricPhysxSurfaceVelocitySchema::Builder::SetSurfaceVelocityEnabled(
    const HdBoolDataSourceHandle &surfaceVelocityEnabled)
{
    _surfaceVelocityEnabled = surfaceVelocityEnabled;
    return *this;
}

FabricPhysxSurfaceVelocitySchema::Builder &
FabricPhysxSurfaceVelocitySchema::Builder::SetSurfaceVelocityLocalSpace(
    const HdBoolDataSourceHandle &surfaceVelocityLocalSpace)
{
    _surfaceVelocityLocalSpace = surfaceVelocityLocalSpace;
    return *this;
}

HdContainerDataSourceHandle
FabricPhysxSurfaceVelocitySchema::Builder::Build()
{
    return FabricPhysxSurfaceVelocitySchema::BuildRetained(
        _surfaceAngularVelocity,
        _surfaceVelocity,
        _surfaceVelocityEnabled,
        _surfaceVelocityLocalSpace
    );
}

/*static*/
FabricPhysxSurfaceVelocitySchema
FabricPhysxSurfaceVelocitySchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricPhysxSurfaceVelocitySchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricPhysxSurfaceVelocitySchemaTokens->physxSurfaceVelocity))
        : nullptr);
}

/*static*/
const TfToken &
FabricPhysxSurfaceVelocitySchema::GetSchemaToken()
{
    return FabricPhysxSurfaceVelocitySchemaTokens->physxSurfaceVelocity;
}

/*static*/
const HdDataSourceLocator &
FabricPhysxSurfaceVelocitySchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxSurfaceVelocitySchema::GetSurfaceAngularVelocityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxSurfaceVelocitySchemaTokens->surfaceAngularVelocity);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocity);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocityEnabledLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityEnabled);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricPhysxSurfaceVelocitySchema::GetSurfaceVelocityLocalSpaceLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricPhysxSurfaceVelocitySchemaTokens->surfaceVelocityLocalSpace);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE