//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/sceneSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricSceneSchemaTokens,
    FABRIC_SCENE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
FabricSceneSchema::GetGravityMagnitude() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricSceneSchemaTokens->gravityMagnitude);
}

HdVec3fDataSourceHandle
FabricSceneSchema::GetGravityDirection() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        FabricSceneSchemaTokens->gravityDirection);
}

/*static*/
HdContainerDataSourceHandle
FabricSceneSchema::BuildRetained(
        const HdFloatDataSourceHandle &gravityMagnitude,
        const HdVec3fDataSourceHandle &gravityDirection
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (gravityMagnitude) {
        _names[_count] = FabricSceneSchemaTokens->gravityMagnitude;
        _values[_count++] = gravityMagnitude;
    }

    if (gravityDirection) {
        _names[_count] = FabricSceneSchemaTokens->gravityDirection;
        _values[_count++] = gravityDirection;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricSceneSchema::Builder &
FabricSceneSchema::Builder::SetGravityMagnitude(
    const HdFloatDataSourceHandle &gravityMagnitude)
{
    _gravityMagnitude = gravityMagnitude;
    return *this;
}

FabricSceneSchema::Builder &
FabricSceneSchema::Builder::SetGravityDirection(
    const HdVec3fDataSourceHandle &gravityDirection)
{
    _gravityDirection = gravityDirection;
    return *this;
}

HdContainerDataSourceHandle
FabricSceneSchema::Builder::Build()
{
    return FabricSceneSchema::BuildRetained(
        _gravityMagnitude,
        _gravityDirection
    );
}

/*static*/
FabricSceneSchema
FabricSceneSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricSceneSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricSceneSchemaTokens->scene))
        : nullptr);
}

/*static*/
const TfToken &
FabricSceneSchema::GetSchemaToken()
{
    return FabricSceneSchemaTokens->scene;
}

/*static*/
const HdDataSourceLocator &
FabricSceneSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricSceneSchema::GetGravityMagnitudeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricSceneSchemaTokens->gravityMagnitude);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricSceneSchema::GetGravityDirectionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricSceneSchemaTokens->gravityDirection);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE