//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/fabric/sphericalJointSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(FabricSphericalJointSchemaTokens,
    FABRIC_SPHERICAL_JOINT_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
FabricSphericalJointSchema::GetAxis() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        FabricSphericalJointSchemaTokens->axis);
}

HdFloatDataSourceHandle
FabricSphericalJointSchema::GetConeAngle0Limit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricSphericalJointSchemaTokens->coneAngle0Limit);
}

HdFloatDataSourceHandle
FabricSphericalJointSchema::GetConeAngle1Limit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        FabricSphericalJointSchemaTokens->coneAngle1Limit);
}

/*static*/
HdContainerDataSourceHandle
FabricSphericalJointSchema::BuildRetained(
        const HdTokenDataSourceHandle &axis,
        const HdFloatDataSourceHandle &coneAngle0Limit,
        const HdFloatDataSourceHandle &coneAngle1Limit
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (axis) {
        _names[_count] = FabricSphericalJointSchemaTokens->axis;
        _values[_count++] = axis;
    }

    if (coneAngle0Limit) {
        _names[_count] = FabricSphericalJointSchemaTokens->coneAngle0Limit;
        _values[_count++] = coneAngle0Limit;
    }

    if (coneAngle1Limit) {
        _names[_count] = FabricSphericalJointSchemaTokens->coneAngle1Limit;
        _values[_count++] = coneAngle1Limit;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

FabricSphericalJointSchema::Builder &
FabricSphericalJointSchema::Builder::SetAxis(
    const HdTokenDataSourceHandle &axis)
{
    _axis = axis;
    return *this;
}

FabricSphericalJointSchema::Builder &
FabricSphericalJointSchema::Builder::SetConeAngle0Limit(
    const HdFloatDataSourceHandle &coneAngle0Limit)
{
    _coneAngle0Limit = coneAngle0Limit;
    return *this;
}

FabricSphericalJointSchema::Builder &
FabricSphericalJointSchema::Builder::SetConeAngle1Limit(
    const HdFloatDataSourceHandle &coneAngle1Limit)
{
    _coneAngle1Limit = coneAngle1Limit;
    return *this;
}

HdContainerDataSourceHandle
FabricSphericalJointSchema::Builder::Build()
{
    return FabricSphericalJointSchema::BuildRetained(
        _axis,
        _coneAngle0Limit,
        _coneAngle1Limit
    );
}

/*static*/
FabricSphericalJointSchema
FabricSphericalJointSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return FabricSphericalJointSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                FabricSphericalJointSchemaTokens->sphericalJoint))
        : nullptr);
}

/*static*/
const TfToken &
FabricSphericalJointSchema::GetSchemaToken()
{
    return FabricSphericalJointSchemaTokens->sphericalJoint;
}

/*static*/
const HdDataSourceLocator &
FabricSphericalJointSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricSphericalJointSchema::GetAxisLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricSphericalJointSchemaTokens->axis);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricSphericalJointSchema::GetConeAngle0LimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricSphericalJointSchemaTokens->coneAngle0Limit);
    return locator;
}

/* static */
const HdDataSourceLocator &
FabricSphericalJointSchema::GetConeAngle1LimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            FabricSphericalJointSchemaTokens->coneAngle1Limit);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE