//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_DIRECT_MATERIAL_BINDINGS_SCHEMA_H
#define PXR_IMAGING_HD_DIRECT_MATERIAL_BINDINGS_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--

#include "pxr/imaging/hd/directMaterialBindingSchema.h"

// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_DIRECT_MATERIAL_BINDINGS_SCHEMA_TOKENS \
    (directMaterialBindings) \
    ((allPurpose, "")) \

TF_DECLARE_PUBLIC_TOKENS(HdDirectMaterialBindingsSchemaTokens, HD_API,
    HD_DIRECT_MATERIAL_BINDINGS_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class HdDirectMaterialBindingsSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdDirectMaterialBindingsSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "directMaterialBindings" from the parent container and constructs a
    /// HdDirectMaterialBindingsSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdDirectMaterialBindingsSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--

    /// Returns the purposes for which bindings may be available.
    /// \note This API is preferable to schema.GetContainer()->GetNames().
    HD_API
    TfTokenVector GetPurposes();

    /// Returns the 'allPurpose' binding.
    HD_API
    HdDirectMaterialBindingSchema
    GetDirectMaterialBinding();

    /// Returns the binding for the requested purpose.
    HD_API
    HdDirectMaterialBindingSchema
    GetDirectMaterialBinding(const TfToken &purpose);

// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{ 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    HD_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @} 

    /// \name Schema construction
    /// @{

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif