//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/directMaterialBindingSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdDirectMaterialBindingSchemaTokens,
    HD_DIRECT_MATERIAL_BINDING_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdPathDataSourceHandle
HdDirectMaterialBindingSchema::GetMaterialPath() const
{
    return _GetTypedDataSource<HdPathDataSource>(
        HdDirectMaterialBindingSchemaTokens->materialPath);
}

HdTokenDataSourceHandle
HdDirectMaterialBindingSchema::GetBindingStrength() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdDirectMaterialBindingSchemaTokens->bindingStrength);
}

/*static*/
HdContainerDataSourceHandle
HdDirectMaterialBindingSchema::BuildRetained(
        const HdPathDataSourceHandle &materialPath,
        const HdTokenDataSourceHandle &bindingStrength
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (materialPath) {
        _names[_count] = HdDirectMaterialBindingSchemaTokens->materialPath;
        _values[_count++] = materialPath;
    }

    if (bindingStrength) {
        _names[_count] = HdDirectMaterialBindingSchemaTokens->bindingStrength;
        _values[_count++] = bindingStrength;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdDirectMaterialBindingSchema::Builder &
HdDirectMaterialBindingSchema::Builder::SetMaterialPath(
    const HdPathDataSourceHandle &materialPath)
{
    _materialPath = materialPath;
    return *this;
}

HdDirectMaterialBindingSchema::Builder &
HdDirectMaterialBindingSchema::Builder::SetBindingStrength(
    const HdTokenDataSourceHandle &bindingStrength)
{
    _bindingStrength = bindingStrength;
    return *this;
}

HdContainerDataSourceHandle
HdDirectMaterialBindingSchema::Builder::Build()
{
    return HdDirectMaterialBindingSchema::BuildRetained(
        _materialPath,
        _bindingStrength
    );
}

/*static*/
HdDirectMaterialBindingSchema
HdDirectMaterialBindingSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdDirectMaterialBindingSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdDirectMaterialBindingSchemaTokens->directMaterialBinding))
        : nullptr);
}

/*static*/
const TfToken &
HdDirectMaterialBindingSchema::GetSchemaToken()
{
    return HdDirectMaterialBindingSchemaTokens->directMaterialBinding;
}

/*static*/
const HdDataSourceLocator &
HdDirectMaterialBindingSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE