//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxCollisionSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxCollisionSchemaTokens,
    HD_PHYSX_COLLISION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxCollisionSchema::GetContactOffset() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxCollisionSchemaTokens->contactOffset);
}

HdFloatDataSourceHandle
HdPhysxCollisionSchema::GetMinTorsionalPatchRadius() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxCollisionSchemaTokens->minTorsionalPatchRadius);
}

HdFloatDataSourceHandle
HdPhysxCollisionSchema::GetRestOffset() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxCollisionSchemaTokens->restOffset);
}

HdFloatDataSourceHandle
HdPhysxCollisionSchema::GetTorsionalPatchRadius() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxCollisionSchemaTokens->torsionalPatchRadius);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxCollisionSchema::BuildRetained(
        const HdFloatDataSourceHandle &contactOffset,
        const HdFloatDataSourceHandle &minTorsionalPatchRadius,
        const HdFloatDataSourceHandle &restOffset,
        const HdFloatDataSourceHandle &torsionalPatchRadius
)
{
    TfToken _names[4];
    HdDataSourceBaseHandle _values[4];

    size_t _count = 0;

    if (contactOffset) {
        _names[_count] = HdPhysxCollisionSchemaTokens->contactOffset;
        _values[_count++] = contactOffset;
    }

    if (minTorsionalPatchRadius) {
        _names[_count] = HdPhysxCollisionSchemaTokens->minTorsionalPatchRadius;
        _values[_count++] = minTorsionalPatchRadius;
    }

    if (restOffset) {
        _names[_count] = HdPhysxCollisionSchemaTokens->restOffset;
        _values[_count++] = restOffset;
    }

    if (torsionalPatchRadius) {
        _names[_count] = HdPhysxCollisionSchemaTokens->torsionalPatchRadius;
        _values[_count++] = torsionalPatchRadius;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxCollisionSchema::Builder &
HdPhysxCollisionSchema::Builder::SetContactOffset(
    const HdFloatDataSourceHandle &contactOffset)
{
    _contactOffset = contactOffset;
    return *this;
}

HdPhysxCollisionSchema::Builder &
HdPhysxCollisionSchema::Builder::SetMinTorsionalPatchRadius(
    const HdFloatDataSourceHandle &minTorsionalPatchRadius)
{
    _minTorsionalPatchRadius = minTorsionalPatchRadius;
    return *this;
}

HdPhysxCollisionSchema::Builder &
HdPhysxCollisionSchema::Builder::SetRestOffset(
    const HdFloatDataSourceHandle &restOffset)
{
    _restOffset = restOffset;
    return *this;
}

HdPhysxCollisionSchema::Builder &
HdPhysxCollisionSchema::Builder::SetTorsionalPatchRadius(
    const HdFloatDataSourceHandle &torsionalPatchRadius)
{
    _torsionalPatchRadius = torsionalPatchRadius;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxCollisionSchema::Builder::Build()
{
    return HdPhysxCollisionSchema::BuildRetained(
        _contactOffset,
        _minTorsionalPatchRadius,
        _restOffset,
        _torsionalPatchRadius
    );
}

/*static*/
HdPhysxCollisionSchema
HdPhysxCollisionSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxCollisionSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxCollisionSchemaTokens->physxCollision))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxCollisionSchema::GetSchemaToken()
{
    return HdPhysxCollisionSchemaTokens->physxCollision;
}

/*static*/
const HdDataSourceLocator &
HdPhysxCollisionSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxCollisionSchema::GetContactOffsetLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxCollisionSchemaTokens->contactOffset);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxCollisionSchema::GetMinTorsionalPatchRadiusLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxCollisionSchemaTokens->minTorsionalPatchRadius);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxCollisionSchema::GetRestOffsetLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxCollisionSchemaTokens->restOffset);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxCollisionSchema::GetTorsionalPatchRadiusLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxCollisionSchemaTokens->torsionalPatchRadius);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE