//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_PHYSX_VEHICLE_CONTROLLER_SCHEMA_H
#define PXR_IMAGING_HD_PHYSX_VEHICLE_CONTROLLER_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_PHYSX_VEHICLE_CONTROLLER_SCHEMA_TOKENS \
    (physxVehicleController) \
    (accelerator) \
    (brake0) \
    (brake1) \
    (steer) \
    (targetGear) \

TF_DECLARE_PUBLIC_TOKENS(HdPhysxVehicleControllerSchemaTokens, HD_API,
    HD_PHYSX_VEHICLE_CONTROLLER_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class HdPhysxVehicleControllerSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdPhysxVehicleControllerSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxVehicleController" from the parent container and constructs a
    /// HdPhysxVehicleControllerSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdPhysxVehicleControllerSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    HD_API
    HdFloatDataSourceHandle GetAccelerator() const;

    HD_API
    HdFloatDataSourceHandle GetBrake0() const;

    HD_API
    HdFloatDataSourceHandle GetBrake1() const;

    HD_API
    HdFloatDataSourceHandle GetSteer() const;

    HD_API
    HdIntDataSourceHandle GetTargetGear() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    HD_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate accelerator.
    HD_API
    static const HdDataSourceLocator &GetAcceleratorLocator();

    /// Prim-level relative data source locator to locate brake0.
    HD_API
    static const HdDataSourceLocator &GetBrake0Locator();

    /// Prim-level relative data source locator to locate brake1.
    HD_API
    static const HdDataSourceLocator &GetBrake1Locator();

    /// Prim-level relative data source locator to locate steer.
    HD_API
    static const HdDataSourceLocator &GetSteerLocator();

    /// Prim-level relative data source locator to locate targetGear.
    HD_API
    static const HdDataSourceLocator &GetTargetGearLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdFloatDataSourceHandle &accelerator,
        const HdFloatDataSourceHandle &brake0,
        const HdFloatDataSourceHandle &brake1,
        const HdFloatDataSourceHandle &steer,
        const HdIntDataSourceHandle &targetGear
    );

    /// \class HdPhysxVehicleControllerSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        HD_API
        Builder &SetAccelerator(
            const HdFloatDataSourceHandle &accelerator);
        HD_API
        Builder &SetBrake0(
            const HdFloatDataSourceHandle &brake0);
        HD_API
        Builder &SetBrake1(
            const HdFloatDataSourceHandle &brake1);
        HD_API
        Builder &SetSteer(
            const HdFloatDataSourceHandle &steer);
        HD_API
        Builder &SetTargetGear(
            const HdIntDataSourceHandle &targetGear);

        /// Returns a container data source containing the members set thus far.
        HD_API
        HdContainerDataSourceHandle Build();

    private:
        HdFloatDataSourceHandle _accelerator;
        HdFloatDataSourceHandle _brake0;
        HdFloatDataSourceHandle _brake1;
        HdFloatDataSourceHandle _steer;
        HdIntDataSourceHandle _targetGear;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif