//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleDriveBasicSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleDriveBasicSchemaTokens,
    HD_PHYSX_VEHICLE_DRIVE_BASIC_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxVehicleDriveBasicSchema::GetPeakTorque() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleDriveBasicSchemaTokens->peakTorque);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxVehicleDriveBasicSchema::BuildRetained(
        const HdFloatDataSourceHandle &peakTorque
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (peakTorque) {
        _names[_count] = HdPhysxVehicleDriveBasicSchemaTokens->peakTorque;
        _values[_count++] = peakTorque;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxVehicleDriveBasicSchema::Builder &
HdPhysxVehicleDriveBasicSchema::Builder::SetPeakTorque(
    const HdFloatDataSourceHandle &peakTorque)
{
    _peakTorque = peakTorque;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxVehicleDriveBasicSchema::Builder::Build()
{
    return HdPhysxVehicleDriveBasicSchema::BuildRetained(
        _peakTorque
    );
}

/*static*/
HdPhysxVehicleDriveBasicSchema
HdPhysxVehicleDriveBasicSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleDriveBasicSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleDriveBasicSchemaTokens->physxVehicleDriveBasic))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleDriveBasicSchema::GetSchemaToken()
{
    return HdPhysxVehicleDriveBasicSchemaTokens->physxVehicleDriveBasic;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleDriveBasicSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleDriveBasicSchema::GetPeakTorqueLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleDriveBasicSchemaTokens->peakTorque);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE