//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxJointSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxJointSchemaTokens,
    HD_PHYSX_JOINT_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxJointSchema::GetArmature() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxJointSchemaTokens->armature);
}

HdBoolDataSourceHandle
HdPhysxJointSchema::GetEnableProjection() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxJointSchemaTokens->enableProjection);
}

HdFloatDataSourceHandle
HdPhysxJointSchema::GetJointFriction() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxJointSchemaTokens->jointFriction);
}

HdFloatDataSourceHandle
HdPhysxJointSchema::GetMaxJointVelocity() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxJointSchemaTokens->maxJointVelocity);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxJointSchema::BuildRetained(
        const HdFloatDataSourceHandle &armature,
        const HdBoolDataSourceHandle &enableProjection,
        const HdFloatDataSourceHandle &jointFriction,
        const HdFloatDataSourceHandle &maxJointVelocity
)
{
    TfToken _names[4];
    HdDataSourceBaseHandle _values[4];

    size_t _count = 0;

    if (armature) {
        _names[_count] = HdPhysxJointSchemaTokens->armature;
        _values[_count++] = armature;
    }

    if (enableProjection) {
        _names[_count] = HdPhysxJointSchemaTokens->enableProjection;
        _values[_count++] = enableProjection;
    }

    if (jointFriction) {
        _names[_count] = HdPhysxJointSchemaTokens->jointFriction;
        _values[_count++] = jointFriction;
    }

    if (maxJointVelocity) {
        _names[_count] = HdPhysxJointSchemaTokens->maxJointVelocity;
        _values[_count++] = maxJointVelocity;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxJointSchema::Builder &
HdPhysxJointSchema::Builder::SetArmature(
    const HdFloatDataSourceHandle &armature)
{
    _armature = armature;
    return *this;
}

HdPhysxJointSchema::Builder &
HdPhysxJointSchema::Builder::SetEnableProjection(
    const HdBoolDataSourceHandle &enableProjection)
{
    _enableProjection = enableProjection;
    return *this;
}

HdPhysxJointSchema::Builder &
HdPhysxJointSchema::Builder::SetJointFriction(
    const HdFloatDataSourceHandle &jointFriction)
{
    _jointFriction = jointFriction;
    return *this;
}

HdPhysxJointSchema::Builder &
HdPhysxJointSchema::Builder::SetMaxJointVelocity(
    const HdFloatDataSourceHandle &maxJointVelocity)
{
    _maxJointVelocity = maxJointVelocity;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxJointSchema::Builder::Build()
{
    return HdPhysxJointSchema::BuildRetained(
        _armature,
        _enableProjection,
        _jointFriction,
        _maxJointVelocity
    );
}

/*static*/
HdPhysxJointSchema
HdPhysxJointSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxJointSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxJointSchemaTokens->physxJoint))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxJointSchema::GetSchemaToken()
{
    return HdPhysxJointSchemaTokens->physxJoint;
}

/*static*/
const HdDataSourceLocator &
HdPhysxJointSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointSchema::GetArmatureLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointSchemaTokens->armature);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointSchema::GetEnableProjectionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointSchemaTokens->enableProjection);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointSchema::GetJointFrictionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointSchemaTokens->jointFriction);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointSchema::GetMaxJointVelocityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointSchemaTokens->maxJointVelocity);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE