//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleTireFrictionTableSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleTireFrictionTableSchemaTokens,
    HD_PHYSX_VEHICLE_TIRE_FRICTION_TABLE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxVehicleTireFrictionTableSchema::GetDefaultFrictionValue() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue);
}

HdFloatArrayDataSourceHandle
HdPhysxVehicleTireFrictionTableSchema::GetFrictionValues() const
{
    return _GetTypedDataSource<HdFloatArrayDataSource>(
        HdPhysxVehicleTireFrictionTableSchemaTokens->frictionValues);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxVehicleTireFrictionTableSchema::BuildRetained(
        const HdFloatDataSourceHandle &defaultFrictionValue,
        const HdFloatArrayDataSourceHandle &frictionValues
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (defaultFrictionValue) {
        _names[_count] = HdPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue;
        _values[_count++] = defaultFrictionValue;
    }

    if (frictionValues) {
        _names[_count] = HdPhysxVehicleTireFrictionTableSchemaTokens->frictionValues;
        _values[_count++] = frictionValues;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxVehicleTireFrictionTableSchema::Builder &
HdPhysxVehicleTireFrictionTableSchema::Builder::SetDefaultFrictionValue(
    const HdFloatDataSourceHandle &defaultFrictionValue)
{
    _defaultFrictionValue = defaultFrictionValue;
    return *this;
}

HdPhysxVehicleTireFrictionTableSchema::Builder &
HdPhysxVehicleTireFrictionTableSchema::Builder::SetFrictionValues(
    const HdFloatArrayDataSourceHandle &frictionValues)
{
    _frictionValues = frictionValues;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxVehicleTireFrictionTableSchema::Builder::Build()
{
    return HdPhysxVehicleTireFrictionTableSchema::BuildRetained(
        _defaultFrictionValue,
        _frictionValues
    );
}

/*static*/
HdPhysxVehicleTireFrictionTableSchema
HdPhysxVehicleTireFrictionTableSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleTireFrictionTableSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleTireFrictionTableSchemaTokens->physxVehicleTireFrictionTable))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleTireFrictionTableSchema::GetSchemaToken()
{
    return HdPhysxVehicleTireFrictionTableSchemaTokens->physxVehicleTireFrictionTable;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleTireFrictionTableSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireFrictionTableSchema::GetDefaultFrictionValueLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireFrictionTableSchemaTokens->defaultFrictionValue);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireFrictionTableSchema::GetFrictionValuesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireFrictionTableSchemaTokens->frictionValues);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE