//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxJointStateSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxJointStateSchemaTokens,
    HD_PHYSX_JOINT_STATE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdPhysxJointStateSchema::GetName() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxJointStateSchemaTokens->name);
}

HdFloatDataSourceHandle
HdPhysxJointStateSchema::GetPosition() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxJointStateSchemaTokens->position);
}

HdFloatDataSourceHandle
HdPhysxJointStateSchema::GetVelocity() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxJointStateSchemaTokens->velocity);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxJointStateSchema::BuildRetained(
        const HdTokenDataSourceHandle &name,
        const HdFloatDataSourceHandle &position,
        const HdFloatDataSourceHandle &velocity
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (name) {
        _names[_count] = HdPhysxJointStateSchemaTokens->name;
        _values[_count++] = name;
    }

    if (position) {
        _names[_count] = HdPhysxJointStateSchemaTokens->position;
        _values[_count++] = position;
    }

    if (velocity) {
        _names[_count] = HdPhysxJointStateSchemaTokens->velocity;
        _values[_count++] = velocity;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxJointStateSchema::Builder &
HdPhysxJointStateSchema::Builder::SetName(
    const HdTokenDataSourceHandle &name)
{
    _name = name;
    return *this;
}

HdPhysxJointStateSchema::Builder &
HdPhysxJointStateSchema::Builder::SetPosition(
    const HdFloatDataSourceHandle &position)
{
    _position = position;
    return *this;
}

HdPhysxJointStateSchema::Builder &
HdPhysxJointStateSchema::Builder::SetVelocity(
    const HdFloatDataSourceHandle &velocity)
{
    _velocity = velocity;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxJointStateSchema::Builder::Build()
{
    return HdPhysxJointStateSchema::BuildRetained(
        _name,
        _position,
        _velocity
    );
}

/*static*/
HdPhysxJointStateSchema
HdPhysxJointStateSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxJointStateSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxJointStateSchemaTokens->physxJointState))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxJointStateSchema::GetSchemaToken()
{
    return HdPhysxJointStateSchemaTokens->physxJointState;
}

/*static*/
const HdDataSourceLocator &
HdPhysxJointStateSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointStateSchema::GetNameLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointStateSchemaTokens->name);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointStateSchema::GetPositionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointStateSchemaTokens->position);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxJointStateSchema::GetVelocityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxJointStateSchemaTokens->velocity);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE