//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleTireSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleTireSchemaTokens,
    HD_PHYSX_VEHICLE_TIRE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxVehicleTireSchema::GetCamberStiffness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleTireSchemaTokens->camberStiffness);
}

HdVec2fArrayDataSourceHandle
HdPhysxVehicleTireSchema::GetFrictionVsSlipGraph() const
{
    return _GetTypedDataSource<HdVec2fArrayDataSource>(
        HdPhysxVehicleTireSchemaTokens->frictionVsSlipGraph);
}

HdVec2fDataSourceHandle
HdPhysxVehicleTireSchema::GetLateralStiffnessGraph() const
{
    return _GetTypedDataSource<HdVec2fDataSource>(
        HdPhysxVehicleTireSchemaTokens->lateralStiffnessGraph);
}

HdFloatDataSourceHandle
HdPhysxVehicleTireSchema::GetLongitudinalStiffness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleTireSchemaTokens->longitudinalStiffness);
}

HdFloatDataSourceHandle
HdPhysxVehicleTireSchema::GetRestLoad() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleTireSchemaTokens->restLoad);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxVehicleTireSchema::BuildRetained(
        const HdFloatDataSourceHandle &camberStiffness,
        const HdVec2fArrayDataSourceHandle &frictionVsSlipGraph,
        const HdVec2fDataSourceHandle &lateralStiffnessGraph,
        const HdFloatDataSourceHandle &longitudinalStiffness,
        const HdFloatDataSourceHandle &restLoad
)
{
    TfToken _names[5];
    HdDataSourceBaseHandle _values[5];

    size_t _count = 0;

    if (camberStiffness) {
        _names[_count] = HdPhysxVehicleTireSchemaTokens->camberStiffness;
        _values[_count++] = camberStiffness;
    }

    if (frictionVsSlipGraph) {
        _names[_count] = HdPhysxVehicleTireSchemaTokens->frictionVsSlipGraph;
        _values[_count++] = frictionVsSlipGraph;
    }

    if (lateralStiffnessGraph) {
        _names[_count] = HdPhysxVehicleTireSchemaTokens->lateralStiffnessGraph;
        _values[_count++] = lateralStiffnessGraph;
    }

    if (longitudinalStiffness) {
        _names[_count] = HdPhysxVehicleTireSchemaTokens->longitudinalStiffness;
        _values[_count++] = longitudinalStiffness;
    }

    if (restLoad) {
        _names[_count] = HdPhysxVehicleTireSchemaTokens->restLoad;
        _values[_count++] = restLoad;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxVehicleTireSchema::Builder &
HdPhysxVehicleTireSchema::Builder::SetCamberStiffness(
    const HdFloatDataSourceHandle &camberStiffness)
{
    _camberStiffness = camberStiffness;
    return *this;
}

HdPhysxVehicleTireSchema::Builder &
HdPhysxVehicleTireSchema::Builder::SetFrictionVsSlipGraph(
    const HdVec2fArrayDataSourceHandle &frictionVsSlipGraph)
{
    _frictionVsSlipGraph = frictionVsSlipGraph;
    return *this;
}

HdPhysxVehicleTireSchema::Builder &
HdPhysxVehicleTireSchema::Builder::SetLateralStiffnessGraph(
    const HdVec2fDataSourceHandle &lateralStiffnessGraph)
{
    _lateralStiffnessGraph = lateralStiffnessGraph;
    return *this;
}

HdPhysxVehicleTireSchema::Builder &
HdPhysxVehicleTireSchema::Builder::SetLongitudinalStiffness(
    const HdFloatDataSourceHandle &longitudinalStiffness)
{
    _longitudinalStiffness = longitudinalStiffness;
    return *this;
}

HdPhysxVehicleTireSchema::Builder &
HdPhysxVehicleTireSchema::Builder::SetRestLoad(
    const HdFloatDataSourceHandle &restLoad)
{
    _restLoad = restLoad;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxVehicleTireSchema::Builder::Build()
{
    return HdPhysxVehicleTireSchema::BuildRetained(
        _camberStiffness,
        _frictionVsSlipGraph,
        _lateralStiffnessGraph,
        _longitudinalStiffness,
        _restLoad
    );
}

/*static*/
HdPhysxVehicleTireSchema
HdPhysxVehicleTireSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleTireSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleTireSchemaTokens->physxVehicleTire))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleTireSchema::GetSchemaToken()
{
    return HdPhysxVehicleTireSchemaTokens->physxVehicleTire;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetCamberStiffnessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireSchemaTokens->camberStiffness);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetFrictionVsSlipGraphLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireSchemaTokens->frictionVsSlipGraph);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetLateralStiffnessGraphLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireSchemaTokens->lateralStiffnessGraph);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetLongitudinalStiffnessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireSchemaTokens->longitudinalStiffness);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleTireSchema::GetRestLoadLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleTireSchemaTokens->restLoad);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE