//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleBrakesEntrySchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleBrakesEntrySchemaTokens,
    HD_PHYSX_VEHICLE_BRAKES_ENTRY_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
HdPhysxVehicleBrakesSchema HdPhysxVehicleBrakesEntrySchema::GetBrakes0Binding() {
    return HdPhysxVehicleBrakesSchema(_GetTypedDataSource<HdContainerDataSource>(HdPhysxVehicleBrakesEntrySchemaTokens->brakes0));
}

HdPhysxVehicleBrakesSchema HdPhysxVehicleBrakesEntrySchema::GetBrakes1Binding() {
    return HdPhysxVehicleBrakesSchema(_GetTypedDataSource<HdContainerDataSource>(HdPhysxVehicleBrakesEntrySchemaTokens->brakes1));
}
// --(END CUSTOM CODE: Schema Methods)--

/*static*/
HdPhysxVehicleBrakesEntrySchema
HdPhysxVehicleBrakesEntrySchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleBrakesEntrySchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleBrakesEntrySchemaTokens->physxVehicleBrakesEntry))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleBrakesEntrySchema::GetSchemaToken()
{
    return HdPhysxVehicleBrakesEntrySchemaTokens->physxVehicleBrakesEntry;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleBrakesEntrySchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE