//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleDriveStandardSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleDriveStandardSchemaTokens,
    HD_PHYSX_VEHICLE_DRIVE_STANDARD_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdPathArrayDataSourceHandle
HdPhysxVehicleDriveStandardSchema::GetGears() const
{
    return _GetTypedDataSource<HdPathArrayDataSource>(
        HdPhysxVehicleDriveStandardSchemaTokens->gears);
}

HdPathArrayDataSourceHandle
HdPhysxVehicleDriveStandardSchema::GetEngine() const
{
    return _GetTypedDataSource<HdPathArrayDataSource>(
        HdPhysxVehicleDriveStandardSchemaTokens->engine);
}

HdPathArrayDataSourceHandle
HdPhysxVehicleDriveStandardSchema::GetAutoGearBox() const
{
    return _GetTypedDataSource<HdPathArrayDataSource>(
        HdPhysxVehicleDriveStandardSchemaTokens->autoGearBox);
}

HdPathArrayDataSourceHandle
HdPhysxVehicleDriveStandardSchema::GetClutch() const
{
    return _GetTypedDataSource<HdPathArrayDataSource>(
        HdPhysxVehicleDriveStandardSchemaTokens->clutch);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxVehicleDriveStandardSchema::BuildRetained(
        const HdPathArrayDataSourceHandle &gears,
        const HdPathArrayDataSourceHandle &engine,
        const HdPathArrayDataSourceHandle &autoGearBox,
        const HdPathArrayDataSourceHandle &clutch
)
{
    TfToken _names[4];
    HdDataSourceBaseHandle _values[4];

    size_t _count = 0;

    if (gears) {
        _names[_count] = HdPhysxVehicleDriveStandardSchemaTokens->gears;
        _values[_count++] = gears;
    }

    if (engine) {
        _names[_count] = HdPhysxVehicleDriveStandardSchemaTokens->engine;
        _values[_count++] = engine;
    }

    if (autoGearBox) {
        _names[_count] = HdPhysxVehicleDriveStandardSchemaTokens->autoGearBox;
        _values[_count++] = autoGearBox;
    }

    if (clutch) {
        _names[_count] = HdPhysxVehicleDriveStandardSchemaTokens->clutch;
        _values[_count++] = clutch;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxVehicleDriveStandardSchema::Builder &
HdPhysxVehicleDriveStandardSchema::Builder::SetGears(
    const HdPathArrayDataSourceHandle &gears)
{
    _gears = gears;
    return *this;
}

HdPhysxVehicleDriveStandardSchema::Builder &
HdPhysxVehicleDriveStandardSchema::Builder::SetEngine(
    const HdPathArrayDataSourceHandle &engine)
{
    _engine = engine;
    return *this;
}

HdPhysxVehicleDriveStandardSchema::Builder &
HdPhysxVehicleDriveStandardSchema::Builder::SetAutoGearBox(
    const HdPathArrayDataSourceHandle &autoGearBox)
{
    _autoGearBox = autoGearBox;
    return *this;
}

HdPhysxVehicleDriveStandardSchema::Builder &
HdPhysxVehicleDriveStandardSchema::Builder::SetClutch(
    const HdPathArrayDataSourceHandle &clutch)
{
    _clutch = clutch;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxVehicleDriveStandardSchema::Builder::Build()
{
    return HdPhysxVehicleDriveStandardSchema::BuildRetained(
        _gears,
        _engine,
        _autoGearBox,
        _clutch
    );
}

/*static*/
HdPhysxVehicleDriveStandardSchema
HdPhysxVehicleDriveStandardSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleDriveStandardSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleDriveStandardSchemaTokens->physxVehicleDriveStandard))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleDriveStandardSchema::GetSchemaToken()
{
    return HdPhysxVehicleDriveStandardSchemaTokens->physxVehicleDriveStandard;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleDriveStandardSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleDriveStandardSchema::GetGearsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleDriveStandardSchemaTokens->gears);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleDriveStandardSchema::GetEngineLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleDriveStandardSchemaTokens->engine);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleDriveStandardSchema::GetAutoGearBoxLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleDriveStandardSchemaTokens->autoGearBox);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleDriveStandardSchema::GetClutchLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleDriveStandardSchemaTokens->clutch);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE