//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxSceneSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxSceneSchemaTokens,
    HD_PHYSX_SCENE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxSceneSchema::GetBounceThreshold() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxSceneSchemaTokens->bounceThreshold);
}

HdTokenDataSourceHandle
HdPhysxSceneSchema::GetBroadphaseType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxSceneSchemaTokens->broadphaseType);
}

HdTokenDataSourceHandle
HdPhysxSceneSchema::GetCollisionSystem() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxSceneSchemaTokens->collisionSystem);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableCCD() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableCCD);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableEnhancedDeterminism() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableEnhancedDeterminism);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableExternalForcesEveryIteration() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableExternalForcesEveryIteration);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableGPUDynamics() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableGPUDynamics);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableResidualReporting() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableResidualReporting);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableSceneQuerySupport() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableSceneQuerySupport);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetEnableStabilization() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->enableStabilization);
}

HdFloatDataSourceHandle
HdPhysxSceneSchema::GetFrictionCorrelationDistance() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxSceneSchemaTokens->frictionCorrelationDistance);
}

HdFloatDataSourceHandle
HdPhysxSceneSchema::GetFrictionOffsetThreshold() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxSceneSchemaTokens->frictionOffsetThreshold);
}

HdTokenDataSourceHandle
HdPhysxSceneSchema::GetFrictionType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxSceneSchemaTokens->frictionType);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuCollisionStackSize() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuCollisionStackSize);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuFoundLostAggregatePairsCapacity() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuFoundLostAggregatePairsCapacity);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuFoundLostPairsCapacity() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuFoundLostPairsCapacity);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuHeapCapacity() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuHeapCapacity);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxDeformableSurfaceContacts() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxDeformableSurfaceContacts);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxHairContacts() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxHairContacts);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxNumPartitions() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxNumPartitions);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxParticleContacts() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxParticleContacts);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxRigidContactCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxRigidContactCount);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxRigidPatchCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxRigidPatchCount);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuMaxSoftBodyContacts() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuMaxSoftBodyContacts);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuTempBufferCapacity() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuTempBufferCapacity);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetGpuTotalAggregatePairsCapacity() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->gpuTotalAggregatePairsCapacity);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetInvertCollisionGroupFilter() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->invertCollisionGroupFilter);
}

HdFloatDataSourceHandle
HdPhysxSceneSchema::GetMaxBiasCoefficient() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxSceneSchemaTokens->maxBiasCoefficient);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetMaxPositionIterationCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->maxPositionIterationCount);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetMaxVelocityIterationCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->maxVelocityIterationCount);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetMinPositionIterationCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->minPositionIterationCount);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetMinVelocityIterationCount() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->minVelocityIterationCount);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetReportKinematicKinematicPairs() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->reportKinematicKinematicPairs);
}

HdBoolDataSourceHandle
HdPhysxSceneSchema::GetReportKinematicStaticPairs() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        HdPhysxSceneSchemaTokens->reportKinematicStaticPairs);
}

HdTokenDataSourceHandle
HdPhysxSceneSchema::GetSolverType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxSceneSchemaTokens->solverType);
}

HdIntDataSourceHandle
HdPhysxSceneSchema::GetTimeStepsPerSecond() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        HdPhysxSceneSchemaTokens->timeStepsPerSecond);
}

HdTokenDataSourceHandle
HdPhysxSceneSchema::GetUpdateType() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPhysxSceneSchemaTokens->updateType);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxSceneSchema::BuildRetained(
        const HdFloatDataSourceHandle &bounceThreshold,
        const HdTokenDataSourceHandle &broadphaseType,
        const HdTokenDataSourceHandle &collisionSystem,
        const HdBoolDataSourceHandle &enableCCD,
        const HdBoolDataSourceHandle &enableEnhancedDeterminism,
        const HdBoolDataSourceHandle &enableExternalForcesEveryIteration,
        const HdBoolDataSourceHandle &enableGPUDynamics,
        const HdBoolDataSourceHandle &enableResidualReporting,
        const HdBoolDataSourceHandle &enableSceneQuerySupport,
        const HdBoolDataSourceHandle &enableStabilization,
        const HdFloatDataSourceHandle &frictionCorrelationDistance,
        const HdFloatDataSourceHandle &frictionOffsetThreshold,
        const HdTokenDataSourceHandle &frictionType,
        const HdIntDataSourceHandle &gpuCollisionStackSize,
        const HdIntDataSourceHandle &gpuFoundLostAggregatePairsCapacity,
        const HdIntDataSourceHandle &gpuFoundLostPairsCapacity,
        const HdIntDataSourceHandle &gpuHeapCapacity,
        const HdIntDataSourceHandle &gpuMaxDeformableSurfaceContacts,
        const HdIntDataSourceHandle &gpuMaxHairContacts,
        const HdIntDataSourceHandle &gpuMaxNumPartitions,
        const HdIntDataSourceHandle &gpuMaxParticleContacts,
        const HdIntDataSourceHandle &gpuMaxRigidContactCount,
        const HdIntDataSourceHandle &gpuMaxRigidPatchCount,
        const HdIntDataSourceHandle &gpuMaxSoftBodyContacts,
        const HdIntDataSourceHandle &gpuTempBufferCapacity,
        const HdIntDataSourceHandle &gpuTotalAggregatePairsCapacity,
        const HdBoolDataSourceHandle &invertCollisionGroupFilter,
        const HdFloatDataSourceHandle &maxBiasCoefficient,
        const HdIntDataSourceHandle &maxPositionIterationCount,
        const HdIntDataSourceHandle &maxVelocityIterationCount,
        const HdIntDataSourceHandle &minPositionIterationCount,
        const HdIntDataSourceHandle &minVelocityIterationCount,
        const HdBoolDataSourceHandle &reportKinematicKinematicPairs,
        const HdBoolDataSourceHandle &reportKinematicStaticPairs,
        const HdTokenDataSourceHandle &solverType,
        const HdIntDataSourceHandle &timeStepsPerSecond,
        const HdTokenDataSourceHandle &updateType
)
{
    TfToken _names[37];
    HdDataSourceBaseHandle _values[37];

    size_t _count = 0;

    if (bounceThreshold) {
        _names[_count] = HdPhysxSceneSchemaTokens->bounceThreshold;
        _values[_count++] = bounceThreshold;
    }

    if (broadphaseType) {
        _names[_count] = HdPhysxSceneSchemaTokens->broadphaseType;
        _values[_count++] = broadphaseType;
    }

    if (collisionSystem) {
        _names[_count] = HdPhysxSceneSchemaTokens->collisionSystem;
        _values[_count++] = collisionSystem;
    }

    if (enableCCD) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableCCD;
        _values[_count++] = enableCCD;
    }

    if (enableEnhancedDeterminism) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableEnhancedDeterminism;
        _values[_count++] = enableEnhancedDeterminism;
    }

    if (enableExternalForcesEveryIteration) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableExternalForcesEveryIteration;
        _values[_count++] = enableExternalForcesEveryIteration;
    }

    if (enableGPUDynamics) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableGPUDynamics;
        _values[_count++] = enableGPUDynamics;
    }

    if (enableResidualReporting) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableResidualReporting;
        _values[_count++] = enableResidualReporting;
    }

    if (enableSceneQuerySupport) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableSceneQuerySupport;
        _values[_count++] = enableSceneQuerySupport;
    }

    if (enableStabilization) {
        _names[_count] = HdPhysxSceneSchemaTokens->enableStabilization;
        _values[_count++] = enableStabilization;
    }

    if (frictionCorrelationDistance) {
        _names[_count] = HdPhysxSceneSchemaTokens->frictionCorrelationDistance;
        _values[_count++] = frictionCorrelationDistance;
    }

    if (frictionOffsetThreshold) {
        _names[_count] = HdPhysxSceneSchemaTokens->frictionOffsetThreshold;
        _values[_count++] = frictionOffsetThreshold;
    }

    if (frictionType) {
        _names[_count] = HdPhysxSceneSchemaTokens->frictionType;
        _values[_count++] = frictionType;
    }

    if (gpuCollisionStackSize) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuCollisionStackSize;
        _values[_count++] = gpuCollisionStackSize;
    }

    if (gpuFoundLostAggregatePairsCapacity) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuFoundLostAggregatePairsCapacity;
        _values[_count++] = gpuFoundLostAggregatePairsCapacity;
    }

    if (gpuFoundLostPairsCapacity) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuFoundLostPairsCapacity;
        _values[_count++] = gpuFoundLostPairsCapacity;
    }

    if (gpuHeapCapacity) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuHeapCapacity;
        _values[_count++] = gpuHeapCapacity;
    }

    if (gpuMaxDeformableSurfaceContacts) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxDeformableSurfaceContacts;
        _values[_count++] = gpuMaxDeformableSurfaceContacts;
    }

    if (gpuMaxHairContacts) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxHairContacts;
        _values[_count++] = gpuMaxHairContacts;
    }

    if (gpuMaxNumPartitions) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxNumPartitions;
        _values[_count++] = gpuMaxNumPartitions;
    }

    if (gpuMaxParticleContacts) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxParticleContacts;
        _values[_count++] = gpuMaxParticleContacts;
    }

    if (gpuMaxRigidContactCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxRigidContactCount;
        _values[_count++] = gpuMaxRigidContactCount;
    }

    if (gpuMaxRigidPatchCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxRigidPatchCount;
        _values[_count++] = gpuMaxRigidPatchCount;
    }

    if (gpuMaxSoftBodyContacts) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuMaxSoftBodyContacts;
        _values[_count++] = gpuMaxSoftBodyContacts;
    }

    if (gpuTempBufferCapacity) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuTempBufferCapacity;
        _values[_count++] = gpuTempBufferCapacity;
    }

    if (gpuTotalAggregatePairsCapacity) {
        _names[_count] = HdPhysxSceneSchemaTokens->gpuTotalAggregatePairsCapacity;
        _values[_count++] = gpuTotalAggregatePairsCapacity;
    }

    if (invertCollisionGroupFilter) {
        _names[_count] = HdPhysxSceneSchemaTokens->invertCollisionGroupFilter;
        _values[_count++] = invertCollisionGroupFilter;
    }

    if (maxBiasCoefficient) {
        _names[_count] = HdPhysxSceneSchemaTokens->maxBiasCoefficient;
        _values[_count++] = maxBiasCoefficient;
    }

    if (maxPositionIterationCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->maxPositionIterationCount;
        _values[_count++] = maxPositionIterationCount;
    }

    if (maxVelocityIterationCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->maxVelocityIterationCount;
        _values[_count++] = maxVelocityIterationCount;
    }

    if (minPositionIterationCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->minPositionIterationCount;
        _values[_count++] = minPositionIterationCount;
    }

    if (minVelocityIterationCount) {
        _names[_count] = HdPhysxSceneSchemaTokens->minVelocityIterationCount;
        _values[_count++] = minVelocityIterationCount;
    }

    if (reportKinematicKinematicPairs) {
        _names[_count] = HdPhysxSceneSchemaTokens->reportKinematicKinematicPairs;
        _values[_count++] = reportKinematicKinematicPairs;
    }

    if (reportKinematicStaticPairs) {
        _names[_count] = HdPhysxSceneSchemaTokens->reportKinematicStaticPairs;
        _values[_count++] = reportKinematicStaticPairs;
    }

    if (solverType) {
        _names[_count] = HdPhysxSceneSchemaTokens->solverType;
        _values[_count++] = solverType;
    }

    if (timeStepsPerSecond) {
        _names[_count] = HdPhysxSceneSchemaTokens->timeStepsPerSecond;
        _values[_count++] = timeStepsPerSecond;
    }

    if (updateType) {
        _names[_count] = HdPhysxSceneSchemaTokens->updateType;
        _values[_count++] = updateType;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetBounceThreshold(
    const HdFloatDataSourceHandle &bounceThreshold)
{
    _bounceThreshold = bounceThreshold;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetBroadphaseType(
    const HdTokenDataSourceHandle &broadphaseType)
{
    _broadphaseType = broadphaseType;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetCollisionSystem(
    const HdTokenDataSourceHandle &collisionSystem)
{
    _collisionSystem = collisionSystem;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableCCD(
    const HdBoolDataSourceHandle &enableCCD)
{
    _enableCCD = enableCCD;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableEnhancedDeterminism(
    const HdBoolDataSourceHandle &enableEnhancedDeterminism)
{
    _enableEnhancedDeterminism = enableEnhancedDeterminism;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableExternalForcesEveryIteration(
    const HdBoolDataSourceHandle &enableExternalForcesEveryIteration)
{
    _enableExternalForcesEveryIteration = enableExternalForcesEveryIteration;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableGPUDynamics(
    const HdBoolDataSourceHandle &enableGPUDynamics)
{
    _enableGPUDynamics = enableGPUDynamics;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableResidualReporting(
    const HdBoolDataSourceHandle &enableResidualReporting)
{
    _enableResidualReporting = enableResidualReporting;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableSceneQuerySupport(
    const HdBoolDataSourceHandle &enableSceneQuerySupport)
{
    _enableSceneQuerySupport = enableSceneQuerySupport;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetEnableStabilization(
    const HdBoolDataSourceHandle &enableStabilization)
{
    _enableStabilization = enableStabilization;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetFrictionCorrelationDistance(
    const HdFloatDataSourceHandle &frictionCorrelationDistance)
{
    _frictionCorrelationDistance = frictionCorrelationDistance;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetFrictionOffsetThreshold(
    const HdFloatDataSourceHandle &frictionOffsetThreshold)
{
    _frictionOffsetThreshold = frictionOffsetThreshold;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetFrictionType(
    const HdTokenDataSourceHandle &frictionType)
{
    _frictionType = frictionType;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuCollisionStackSize(
    const HdIntDataSourceHandle &gpuCollisionStackSize)
{
    _gpuCollisionStackSize = gpuCollisionStackSize;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuFoundLostAggregatePairsCapacity(
    const HdIntDataSourceHandle &gpuFoundLostAggregatePairsCapacity)
{
    _gpuFoundLostAggregatePairsCapacity = gpuFoundLostAggregatePairsCapacity;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuFoundLostPairsCapacity(
    const HdIntDataSourceHandle &gpuFoundLostPairsCapacity)
{
    _gpuFoundLostPairsCapacity = gpuFoundLostPairsCapacity;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuHeapCapacity(
    const HdIntDataSourceHandle &gpuHeapCapacity)
{
    _gpuHeapCapacity = gpuHeapCapacity;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxDeformableSurfaceContacts(
    const HdIntDataSourceHandle &gpuMaxDeformableSurfaceContacts)
{
    _gpuMaxDeformableSurfaceContacts = gpuMaxDeformableSurfaceContacts;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxHairContacts(
    const HdIntDataSourceHandle &gpuMaxHairContacts)
{
    _gpuMaxHairContacts = gpuMaxHairContacts;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxNumPartitions(
    const HdIntDataSourceHandle &gpuMaxNumPartitions)
{
    _gpuMaxNumPartitions = gpuMaxNumPartitions;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxParticleContacts(
    const HdIntDataSourceHandle &gpuMaxParticleContacts)
{
    _gpuMaxParticleContacts = gpuMaxParticleContacts;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxRigidContactCount(
    const HdIntDataSourceHandle &gpuMaxRigidContactCount)
{
    _gpuMaxRigidContactCount = gpuMaxRigidContactCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxRigidPatchCount(
    const HdIntDataSourceHandle &gpuMaxRigidPatchCount)
{
    _gpuMaxRigidPatchCount = gpuMaxRigidPatchCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuMaxSoftBodyContacts(
    const HdIntDataSourceHandle &gpuMaxSoftBodyContacts)
{
    _gpuMaxSoftBodyContacts = gpuMaxSoftBodyContacts;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuTempBufferCapacity(
    const HdIntDataSourceHandle &gpuTempBufferCapacity)
{
    _gpuTempBufferCapacity = gpuTempBufferCapacity;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetGpuTotalAggregatePairsCapacity(
    const HdIntDataSourceHandle &gpuTotalAggregatePairsCapacity)
{
    _gpuTotalAggregatePairsCapacity = gpuTotalAggregatePairsCapacity;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetInvertCollisionGroupFilter(
    const HdBoolDataSourceHandle &invertCollisionGroupFilter)
{
    _invertCollisionGroupFilter = invertCollisionGroupFilter;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetMaxBiasCoefficient(
    const HdFloatDataSourceHandle &maxBiasCoefficient)
{
    _maxBiasCoefficient = maxBiasCoefficient;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetMaxPositionIterationCount(
    const HdIntDataSourceHandle &maxPositionIterationCount)
{
    _maxPositionIterationCount = maxPositionIterationCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetMaxVelocityIterationCount(
    const HdIntDataSourceHandle &maxVelocityIterationCount)
{
    _maxVelocityIterationCount = maxVelocityIterationCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetMinPositionIterationCount(
    const HdIntDataSourceHandle &minPositionIterationCount)
{
    _minPositionIterationCount = minPositionIterationCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetMinVelocityIterationCount(
    const HdIntDataSourceHandle &minVelocityIterationCount)
{
    _minVelocityIterationCount = minVelocityIterationCount;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetReportKinematicKinematicPairs(
    const HdBoolDataSourceHandle &reportKinematicKinematicPairs)
{
    _reportKinematicKinematicPairs = reportKinematicKinematicPairs;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetReportKinematicStaticPairs(
    const HdBoolDataSourceHandle &reportKinematicStaticPairs)
{
    _reportKinematicStaticPairs = reportKinematicStaticPairs;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetSolverType(
    const HdTokenDataSourceHandle &solverType)
{
    _solverType = solverType;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetTimeStepsPerSecond(
    const HdIntDataSourceHandle &timeStepsPerSecond)
{
    _timeStepsPerSecond = timeStepsPerSecond;
    return *this;
}

HdPhysxSceneSchema::Builder &
HdPhysxSceneSchema::Builder::SetUpdateType(
    const HdTokenDataSourceHandle &updateType)
{
    _updateType = updateType;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxSceneSchema::Builder::Build()
{
    return HdPhysxSceneSchema::BuildRetained(
        _bounceThreshold,
        _broadphaseType,
        _collisionSystem,
        _enableCCD,
        _enableEnhancedDeterminism,
        _enableExternalForcesEveryIteration,
        _enableGPUDynamics,
        _enableResidualReporting,
        _enableSceneQuerySupport,
        _enableStabilization,
        _frictionCorrelationDistance,
        _frictionOffsetThreshold,
        _frictionType,
        _gpuCollisionStackSize,
        _gpuFoundLostAggregatePairsCapacity,
        _gpuFoundLostPairsCapacity,
        _gpuHeapCapacity,
        _gpuMaxDeformableSurfaceContacts,
        _gpuMaxHairContacts,
        _gpuMaxNumPartitions,
        _gpuMaxParticleContacts,
        _gpuMaxRigidContactCount,
        _gpuMaxRigidPatchCount,
        _gpuMaxSoftBodyContacts,
        _gpuTempBufferCapacity,
        _gpuTotalAggregatePairsCapacity,
        _invertCollisionGroupFilter,
        _maxBiasCoefficient,
        _maxPositionIterationCount,
        _maxVelocityIterationCount,
        _minPositionIterationCount,
        _minVelocityIterationCount,
        _reportKinematicKinematicPairs,
        _reportKinematicStaticPairs,
        _solverType,
        _timeStepsPerSecond,
        _updateType
    );
}

/*static*/
HdPhysxSceneSchema
HdPhysxSceneSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxSceneSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxSceneSchemaTokens->physxScene))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxSceneSchema::GetSchemaToken()
{
    return HdPhysxSceneSchemaTokens->physxScene;
}

/*static*/
const HdDataSourceLocator &
HdPhysxSceneSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetBounceThresholdLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->bounceThreshold);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetBroadphaseTypeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->broadphaseType);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetCollisionSystemLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->collisionSystem);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableCCDLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableCCD);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableEnhancedDeterminismLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableEnhancedDeterminism);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableExternalForcesEveryIterationLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableExternalForcesEveryIteration);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableGPUDynamicsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableGPUDynamics);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableResidualReportingLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableResidualReporting);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableSceneQuerySupportLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableSceneQuerySupport);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetEnableStabilizationLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->enableStabilization);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetFrictionCorrelationDistanceLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->frictionCorrelationDistance);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetFrictionOffsetThresholdLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->frictionOffsetThreshold);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetFrictionTypeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->frictionType);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuCollisionStackSizeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuCollisionStackSize);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuFoundLostAggregatePairsCapacityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuFoundLostAggregatePairsCapacity);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuFoundLostPairsCapacityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuFoundLostPairsCapacity);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuHeapCapacityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuHeapCapacity);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxDeformableSurfaceContactsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxDeformableSurfaceContacts);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxHairContactsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxHairContacts);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxNumPartitionsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxNumPartitions);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxParticleContactsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxParticleContacts);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxRigidContactCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxRigidContactCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxRigidPatchCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxRigidPatchCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuMaxSoftBodyContactsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuMaxSoftBodyContacts);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuTempBufferCapacityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuTempBufferCapacity);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetGpuTotalAggregatePairsCapacityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->gpuTotalAggregatePairsCapacity);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetInvertCollisionGroupFilterLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->invertCollisionGroupFilter);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetMaxBiasCoefficientLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->maxBiasCoefficient);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetMaxPositionIterationCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->maxPositionIterationCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetMaxVelocityIterationCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->maxVelocityIterationCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetMinPositionIterationCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->minPositionIterationCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetMinVelocityIterationCountLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->minVelocityIterationCount);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetReportKinematicKinematicPairsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->reportKinematicKinematicPairs);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetReportKinematicStaticPairsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->reportKinematicStaticPairs);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetSolverTypeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->solverType);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetTimeStepsPerSecondLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->timeStepsPerSecond);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxSceneSchema::GetUpdateTypeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxSceneSchemaTokens->updateType);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE