//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxPhysicsInstancerSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxPhysicsInstancerSchemaTokens,
    HD_PHYSX_PHYSICS_INSTANCER_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdIntArrayDataSourceHandle
HdPhysxPhysicsInstancerSchema::GetProtoIndices() const
{
    return _GetTypedDataSource<HdIntArrayDataSource>(
        HdPhysxPhysicsInstancerSchemaTokens->protoIndices);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxPhysicsInstancerSchema::BuildRetained(
        const HdIntArrayDataSourceHandle &protoIndices
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (protoIndices) {
        _names[_count] = HdPhysxPhysicsInstancerSchemaTokens->protoIndices;
        _values[_count++] = protoIndices;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxPhysicsInstancerSchema::Builder &
HdPhysxPhysicsInstancerSchema::Builder::SetProtoIndices(
    const HdIntArrayDataSourceHandle &protoIndices)
{
    _protoIndices = protoIndices;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxPhysicsInstancerSchema::Builder::Build()
{
    return HdPhysxPhysicsInstancerSchema::BuildRetained(
        _protoIndices
    );
}

/*static*/
HdPhysxPhysicsInstancerSchema
HdPhysxPhysicsInstancerSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxPhysicsInstancerSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxPhysicsInstancerSchemaTokens->physxPhysicsInstancer))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxPhysicsInstancerSchema::GetSchemaToken()
{
    return HdPhysxPhysicsInstancerSchemaTokens->physxPhysicsInstancer;
}

/*static*/
const HdDataSourceLocator &
HdPhysxPhysicsInstancerSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxPhysicsInstancerSchema::GetProtoIndicesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxPhysicsInstancerSchemaTokens->protoIndices);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE