//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/physxVehicleClutchSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPhysxVehicleClutchSchemaTokens,
    HD_PHYSX_VEHICLE_CLUTCH_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
HdPhysxVehicleClutchSchema::GetStrength() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPhysxVehicleClutchSchemaTokens->strength);
}

/*static*/
HdContainerDataSourceHandle
HdPhysxVehicleClutchSchema::BuildRetained(
        const HdFloatDataSourceHandle &strength
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (strength) {
        _names[_count] = HdPhysxVehicleClutchSchemaTokens->strength;
        _values[_count++] = strength;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPhysxVehicleClutchSchema::Builder &
HdPhysxVehicleClutchSchema::Builder::SetStrength(
    const HdFloatDataSourceHandle &strength)
{
    _strength = strength;
    return *this;
}

HdContainerDataSourceHandle
HdPhysxVehicleClutchSchema::Builder::Build()
{
    return HdPhysxVehicleClutchSchema::BuildRetained(
        _strength
    );
}

/*static*/
HdPhysxVehicleClutchSchema
HdPhysxVehicleClutchSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPhysxVehicleClutchSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPhysxVehicleClutchSchemaTokens->physxVehicleClutch))
        : nullptr);
}

/*static*/
const TfToken &
HdPhysxVehicleClutchSchema::GetSchemaToken()
{
    return HdPhysxVehicleClutchSchemaTokens->physxVehicleClutch;
}

/*static*/
const HdDataSourceLocator &
HdPhysxVehicleClutchSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPhysxVehicleClutchSchema::GetStrengthLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPhysxVehicleClutchSchemaTokens->strength);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE