//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_PHYSX_RESIDUAL_REPORTING_SCHEMA_H
#define PXR_IMAGING_HD_PHYSX_RESIDUAL_REPORTING_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_PHYSX_RESIDUAL_REPORTING_SCHEMA_TOKENS \
    (physxResidualReporting) \
    (maxResidualPositionIteration) \
    (maxResidualVelocityIteration) \
    (rmsResidualPositionIteration) \
    (rmsResidualVelocityIteration) \

TF_DECLARE_PUBLIC_TOKENS(HdPhysxResidualReportingSchemaTokens, HD_API,
    HD_PHYSX_RESIDUAL_REPORTING_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class HdPhysxResidualReportingSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdPhysxResidualReportingSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxResidualReporting" from the parent container and constructs a
    /// HdPhysxResidualReportingSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdPhysxResidualReportingSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    HD_API
    HdFloatDataSourceHandle GetMaxResidualPositionIteration() const;

    HD_API
    HdFloatDataSourceHandle GetMaxResidualVelocityIteration() const;

    HD_API
    HdFloatDataSourceHandle GetRmsResidualPositionIteration() const;

    HD_API
    HdFloatDataSourceHandle GetRmsResidualVelocityIteration() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    HD_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate maxResidualPositionIteration.
    HD_API
    static const HdDataSourceLocator &GetMaxResidualPositionIterationLocator();

    /// Prim-level relative data source locator to locate maxResidualVelocityIteration.
    HD_API
    static const HdDataSourceLocator &GetMaxResidualVelocityIterationLocator();

    /// Prim-level relative data source locator to locate rmsResidualPositionIteration.
    HD_API
    static const HdDataSourceLocator &GetRmsResidualPositionIterationLocator();

    /// Prim-level relative data source locator to locate rmsResidualVelocityIteration.
    HD_API
    static const HdDataSourceLocator &GetRmsResidualVelocityIterationLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdFloatDataSourceHandle &maxResidualPositionIteration,
        const HdFloatDataSourceHandle &maxResidualVelocityIteration,
        const HdFloatDataSourceHandle &rmsResidualPositionIteration,
        const HdFloatDataSourceHandle &rmsResidualVelocityIteration
    );

    /// \class HdPhysxResidualReportingSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        HD_API
        Builder &SetMaxResidualPositionIteration(
            const HdFloatDataSourceHandle &maxResidualPositionIteration);
        HD_API
        Builder &SetMaxResidualVelocityIteration(
            const HdFloatDataSourceHandle &maxResidualVelocityIteration);
        HD_API
        Builder &SetRmsResidualPositionIteration(
            const HdFloatDataSourceHandle &rmsResidualPositionIteration);
        HD_API
        Builder &SetRmsResidualVelocityIteration(
            const HdFloatDataSourceHandle &rmsResidualVelocityIteration);

        /// Returns a container data source containing the members set thus far.
        HD_API
        HdContainerDataSourceHandle Build();

    private:
        HdFloatDataSourceHandle _maxResidualPositionIteration;
        HdFloatDataSourceHandle _maxResidualVelocityIteration;
        HdFloatDataSourceHandle _rmsResidualPositionIteration;
        HdFloatDataSourceHandle _rmsResidualVelocityIteration;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif