//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/imaging/hd/prismaticJointSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(HdPrismaticJointSchemaTokens,
    HD_PRISMATIC_JOINT_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
HdPrismaticJointSchema::GetAxis() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        HdPrismaticJointSchemaTokens->axis);
}

HdFloatDataSourceHandle
HdPrismaticJointSchema::GetLowerLimit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPrismaticJointSchemaTokens->lowerLimit);
}

HdFloatDataSourceHandle
HdPrismaticJointSchema::GetUpperLimit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        HdPrismaticJointSchemaTokens->upperLimit);
}

/*static*/
HdContainerDataSourceHandle
HdPrismaticJointSchema::BuildRetained(
        const HdTokenDataSourceHandle &axis,
        const HdFloatDataSourceHandle &lowerLimit,
        const HdFloatDataSourceHandle &upperLimit
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (axis) {
        _names[_count] = HdPrismaticJointSchemaTokens->axis;
        _values[_count++] = axis;
    }

    if (lowerLimit) {
        _names[_count] = HdPrismaticJointSchemaTokens->lowerLimit;
        _values[_count++] = lowerLimit;
    }

    if (upperLimit) {
        _names[_count] = HdPrismaticJointSchemaTokens->upperLimit;
        _values[_count++] = upperLimit;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

HdPrismaticJointSchema::Builder &
HdPrismaticJointSchema::Builder::SetAxis(
    const HdTokenDataSourceHandle &axis)
{
    _axis = axis;
    return *this;
}

HdPrismaticJointSchema::Builder &
HdPrismaticJointSchema::Builder::SetLowerLimit(
    const HdFloatDataSourceHandle &lowerLimit)
{
    _lowerLimit = lowerLimit;
    return *this;
}

HdPrismaticJointSchema::Builder &
HdPrismaticJointSchema::Builder::SetUpperLimit(
    const HdFloatDataSourceHandle &upperLimit)
{
    _upperLimit = upperLimit;
    return *this;
}

HdContainerDataSourceHandle
HdPrismaticJointSchema::Builder::Build()
{
    return HdPrismaticJointSchema::BuildRetained(
        _axis,
        _lowerLimit,
        _upperLimit
    );
}

/*static*/
HdPrismaticJointSchema
HdPrismaticJointSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return HdPrismaticJointSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                HdPrismaticJointSchemaTokens->prismaticJoint))
        : nullptr);
}

/*static*/
const TfToken &
HdPrismaticJointSchema::GetSchemaToken()
{
    return HdPrismaticJointSchemaTokens->prismaticJoint;
}

/*static*/
const HdDataSourceLocator &
HdPrismaticJointSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPrismaticJointSchema::GetAxisLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPrismaticJointSchemaTokens->axis);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPrismaticJointSchema::GetLowerLimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPrismaticJointSchemaTokens->lowerLimit);
    return locator;
}

/* static */
const HdDataSourceLocator &
HdPrismaticJointSchema::GetUpperLimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            HdPrismaticJointSchemaTokens->upperLimit);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE