//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_IMAGING_HD_RIGID_BODY_SCHEMA_H
#define PXR_IMAGING_HD_RIGID_BODY_SCHEMA_H

/// \file

#include "pxr/imaging/hd/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define HD_RIGID_BODY_SCHEMA_TOKENS \
    (rigidBody) \
    (rigidBodyEnabled) \
    (kinematicEnabled) \
    (startsAsleep) \
    (velocity) \
    (angularVelocity) \
    (simulationOwner) \

TF_DECLARE_PUBLIC_TOKENS(HdRigidBodySchemaTokens, HD_API,
    HD_RIGID_BODY_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class HdRigidBodySchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    HdRigidBodySchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "rigidBody" from the parent container and constructs a
    /// HdRigidBodySchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    HD_API
    static HdRigidBodySchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    HD_API
    HdBoolDataSourceHandle GetRigidBodyEnabled() const;

    HD_API
    HdBoolDataSourceHandle GetKinematicEnabled() const;

    HD_API
    HdBoolDataSourceHandle GetStartsAsleep() const;

    HD_API
    HdVec3fDataSourceHandle GetVelocity() const;

    HD_API
    HdVec3fDataSourceHandle GetAngularVelocity() const;

    HD_API
    HdPathArrayDataSourceHandle GetSimulationOwner() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    HD_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    HD_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate rigidBodyEnabled.
    HD_API
    static const HdDataSourceLocator &GetRigidBodyEnabledLocator();

    /// Prim-level relative data source locator to locate kinematicEnabled.
    HD_API
    static const HdDataSourceLocator &GetKinematicEnabledLocator();

    /// Prim-level relative data source locator to locate startsAsleep.
    HD_API
    static const HdDataSourceLocator &GetStartsAsleepLocator();

    /// Prim-level relative data source locator to locate velocity.
    HD_API
    static const HdDataSourceLocator &GetVelocityLocator();

    /// Prim-level relative data source locator to locate angularVelocity.
    HD_API
    static const HdDataSourceLocator &GetAngularVelocityLocator();

    /// Prim-level relative data source locator to locate simulationOwner.
    HD_API
    static const HdDataSourceLocator &GetSimulationOwnerLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    HD_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdBoolDataSourceHandle &rigidBodyEnabled,
        const HdBoolDataSourceHandle &kinematicEnabled,
        const HdBoolDataSourceHandle &startsAsleep,
        const HdVec3fDataSourceHandle &velocity,
        const HdVec3fDataSourceHandle &angularVelocity,
        const HdPathArrayDataSourceHandle &simulationOwner
    );

    /// \class HdRigidBodySchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        HD_API
        Builder &SetRigidBodyEnabled(
            const HdBoolDataSourceHandle &rigidBodyEnabled);
        HD_API
        Builder &SetKinematicEnabled(
            const HdBoolDataSourceHandle &kinematicEnabled);
        HD_API
        Builder &SetStartsAsleep(
            const HdBoolDataSourceHandle &startsAsleep);
        HD_API
        Builder &SetVelocity(
            const HdVec3fDataSourceHandle &velocity);
        HD_API
        Builder &SetAngularVelocity(
            const HdVec3fDataSourceHandle &angularVelocity);
        HD_API
        Builder &SetSimulationOwner(
            const HdPathArrayDataSourceHandle &simulationOwner);

        /// Returns a container data source containing the members set thus far.
        HD_API
        HdContainerDataSourceHandle Build();

    private:
        HdBoolDataSourceHandle _rigidBodyEnabled;
        HdBoolDataSourceHandle _kinematicEnabled;
        HdBoolDataSourceHandle _startsAsleep;
        HdVec3fDataSourceHandle _velocity;
        HdVec3fDataSourceHandle _angularVelocity;
        HdPathArrayDataSourceHandle _simulationOwner;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif