//
// Copyright 2024 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//

// WARNING: THIS FILE IS GENERATED BY usdGenSchema.  DO NOT EDIT.
TF_WRAP(UsdPhysXJointStateAPI);
TF_WRAP(UsdPhysXArticulationAPI);
TF_WRAP(UsdPhysXCameraAPI);
TF_WRAP(UsdPhysXCameraDroneAPI);
TF_WRAP(UsdPhysXCameraFollowAPI);
TF_WRAP(UsdPhysXCameraFollowLookAPI);
TF_WRAP(UsdPhysXCameraFollowVelocityAPI);
TF_WRAP(UsdPhysXCharacterControllerAPI);
TF_WRAP(UsdPhysXCollisionAPI);
TF_WRAP(UsdPhysXContactReportAPI);
TF_WRAP(UsdPhysXConvexDecompositionCollisionAPI);
TF_WRAP(UsdPhysXConvexHullCollisionAPI);
TF_WRAP(UsdPhysXCookedDataAPI);
TF_WRAP(UsdPhysXForceAPI);
TF_WRAP(UsdPhysXIsosurfaceAPI);
TF_WRAP(UsdPhysXJointAPI);
TF_WRAP(UsdPhysXMaterialAPI);
TF_WRAP(UsdPhysXMeshMergeCollisionAPI);
TF_WRAP(UsdPhysXMimicJointAPI);
TF_WRAP(UsdPhysXPhysicsDistanceJointAPI);
TF_WRAP(UsdPhysXPhysicsGearJoint);
TF_WRAP(UsdPhysXPhysicsInstancer);
TF_WRAP(UsdPhysXTokens);
