//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "pxr/usd/usdPhysX/tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdPhysXTokensType::UsdPhysXTokensType() :
    alwaysUpdateEnabled("alwaysUpdateEnabled", TfToken::Immortal),
    jointState("jointState", TfToken::Immortal),
    jointState_MultipleApplyTemplate_PhysicsPosition("jointState:__INSTANCE_NAME__:physics:position", TfToken::Immortal),
    jointState_MultipleApplyTemplate_PhysicsVelocity("jointState:__INSTANCE_NAME__:physics:velocity", TfToken::Immortal),
    physxArticulationArticulationEnabled("physxArticulation:articulationEnabled", TfToken::Immortal),
    physxArticulationEnabledSelfCollisions("physxArticulation:enabledSelfCollisions", TfToken::Immortal),
    physxArticulationSleepThreshold("physxArticulation:sleepThreshold", TfToken::Immortal),
    physxArticulationSolverPositionIterationCount("physxArticulation:solverPositionIterationCount", TfToken::Immortal),
    physxArticulationSolverVelocityIterationCount("physxArticulation:solverVelocityIterationCount", TfToken::Immortal),
    physxArticulationStabilizationThreshold("physxArticulation:stabilizationThreshold", TfToken::Immortal),
    physxDroneCameraFeedForwardVelocityGain("physxDroneCamera:feedForwardVelocityGain", TfToken::Immortal),
    physxDroneCameraFollowDistance("physxDroneCamera:followDistance", TfToken::Immortal),
    physxDroneCameraFollowHeight("physxDroneCamera:followHeight", TfToken::Immortal),
    physxDroneCameraHorizontalVelocityGain("physxDroneCamera:horizontalVelocityGain", TfToken::Immortal),
    physxDroneCameraMaxDistance("physxDroneCamera:maxDistance", TfToken::Immortal),
    physxDroneCameraMaxSpeed("physxDroneCamera:maxSpeed", TfToken::Immortal),
    physxDroneCameraPositionOffset("physxDroneCamera:positionOffset", TfToken::Immortal),
    physxDroneCameraRotationFilterTimeConstant("physxDroneCamera:rotationFilterTimeConstant", TfToken::Immortal),
    physxDroneCameraVelocityFilterTimeConstant("physxDroneCamera:velocityFilterTimeConstant", TfToken::Immortal),
    physxDroneCameraVerticalVelocityGain("physxDroneCamera:verticalVelocityGain", TfToken::Immortal),
    physxFollowCameraCameraPositionTimeConstant("physxFollowCamera:cameraPositionTimeConstant", TfToken::Immortal),
    physxFollowCameraFollowMaxDistance("physxFollowCamera:followMaxDistance", TfToken::Immortal),
    physxFollowCameraFollowMaxSpeed("physxFollowCamera:followMaxSpeed", TfToken::Immortal),
    physxFollowCameraFollowMinDistance("physxFollowCamera:followMinDistance", TfToken::Immortal),
    physxFollowCameraFollowMinSpeed("physxFollowCamera:followMinSpeed", TfToken::Immortal),
    physxFollowCameraFollowTurnRateGain("physxFollowCamera:followTurnRateGain", TfToken::Immortal),
    physxFollowCameraLookAheadMaxSpeed("physxFollowCamera:lookAheadMaxSpeed", TfToken::Immortal),
    physxFollowCameraLookAheadMinDistance("physxFollowCamera:lookAheadMinDistance", TfToken::Immortal),
    physxFollowCameraLookAheadMinSpeed("physxFollowCamera:lookAheadMinSpeed", TfToken::Immortal),
    physxFollowCameraLookAheadTurnRateGain("physxFollowCamera:lookAheadTurnRateGain", TfToken::Immortal),
    physxFollowCameraLookPositionHeight("physxFollowCamera:lookPositionHeight", TfToken::Immortal),
    physxFollowCameraLookPositionTimeConstant("physxFollowCamera:lookPositionTimeConstant", TfToken::Immortal),
    physxFollowCameraPitchAngle("physxFollowCamera:pitchAngle", TfToken::Immortal),
    physxFollowCameraPitchAngleTimeConstant("physxFollowCamera:pitchAngleTimeConstant", TfToken::Immortal),
    physxFollowCameraPositionOffset("physxFollowCamera:positionOffset", TfToken::Immortal),
    physxFollowCameraSlowPitchAngleSpeed("physxFollowCamera:slowPitchAngleSpeed", TfToken::Immortal),
    physxFollowCameraSlowSpeedPitchAngleScale("physxFollowCamera:slowSpeedPitchAngleScale", TfToken::Immortal),
    physxFollowCameraVelocityNormalMinSpeed("physxFollowCamera:velocityNormalMinSpeed", TfToken::Immortal),
    physxFollowCameraYawAngle("physxFollowCamera:yawAngle", TfToken::Immortal),
    physxFollowCameraYawRateTimeConstant("physxFollowCamera:yawRateTimeConstant", TfToken::Immortal),
    physxFollowFollowCameraLookAheadMaxDistance("physxFollowFollowCamera:lookAheadMaxDistance", TfToken::Immortal),
    physxFollowLookCameraDownHillGroundAngle("physxFollowLookCamera:downHillGroundAngle", TfToken::Immortal),
    physxFollowLookCameraDownHillGroundPitch("physxFollowLookCamera:downHillGroundPitch", TfToken::Immortal),
    physxFollowLookCameraFollowReverseDistance("physxFollowLookCamera:followReverseDistance", TfToken::Immortal),
    physxFollowLookCameraFollowReverseSpeed("physxFollowLookCamera:followReverseSpeed", TfToken::Immortal),
    physxFollowLookCameraUpHillGroundAngle("physxFollowLookCamera:upHillGroundAngle", TfToken::Immortal),
    physxFollowLookCameraUpHillGroundPitch("physxFollowLookCamera:upHillGroundPitch", TfToken::Immortal),
    physxFollowLookCameraVelocityBlendTimeConstant("physxFollowLookCamera:velocityBlendTimeConstant", TfToken::Immortal),
    PhysxSchemaJointStateAPI("PhysxSchemaJointStateAPI", TfToken::Immortal),
    PhysxSchemaPhysxArticulationAPI("PhysxSchemaPhysxArticulationAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraAPI("PhysxSchemaPhysxCameraAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraDroneAPI("PhysxSchemaPhysxCameraDroneAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowAPI("PhysxSchemaPhysxCameraFollowAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowLookAPI("PhysxSchemaPhysxCameraFollowLookAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowVelocityAPI("PhysxSchemaPhysxCameraFollowVelocityAPI", TfToken::Immortal),
    allTokens({
        alwaysUpdateEnabled,
        jointState,
        jointState_MultipleApplyTemplate_PhysicsPosition,
        jointState_MultipleApplyTemplate_PhysicsVelocity,
        physxArticulationArticulationEnabled,
        physxArticulationEnabledSelfCollisions,
        physxArticulationSleepThreshold,
        physxArticulationSolverPositionIterationCount,
        physxArticulationSolverVelocityIterationCount,
        physxArticulationStabilizationThreshold,
        physxDroneCameraFeedForwardVelocityGain,
        physxDroneCameraFollowDistance,
        physxDroneCameraFollowHeight,
        physxDroneCameraHorizontalVelocityGain,
        physxDroneCameraMaxDistance,
        physxDroneCameraMaxSpeed,
        physxDroneCameraPositionOffset,
        physxDroneCameraRotationFilterTimeConstant,
        physxDroneCameraVelocityFilterTimeConstant,
        physxDroneCameraVerticalVelocityGain,
        physxFollowCameraCameraPositionTimeConstant,
        physxFollowCameraFollowMaxDistance,
        physxFollowCameraFollowMaxSpeed,
        physxFollowCameraFollowMinDistance,
        physxFollowCameraFollowMinSpeed,
        physxFollowCameraFollowTurnRateGain,
        physxFollowCameraLookAheadMaxSpeed,
        physxFollowCameraLookAheadMinDistance,
        physxFollowCameraLookAheadMinSpeed,
        physxFollowCameraLookAheadTurnRateGain,
        physxFollowCameraLookPositionHeight,
        physxFollowCameraLookPositionTimeConstant,
        physxFollowCameraPitchAngle,
        physxFollowCameraPitchAngleTimeConstant,
        physxFollowCameraPositionOffset,
        physxFollowCameraSlowPitchAngleSpeed,
        physxFollowCameraSlowSpeedPitchAngleScale,
        physxFollowCameraVelocityNormalMinSpeed,
        physxFollowCameraYawAngle,
        physxFollowCameraYawRateTimeConstant,
        physxFollowFollowCameraLookAheadMaxDistance,
        physxFollowLookCameraDownHillGroundAngle,
        physxFollowLookCameraDownHillGroundPitch,
        physxFollowLookCameraFollowReverseDistance,
        physxFollowLookCameraFollowReverseSpeed,
        physxFollowLookCameraUpHillGroundAngle,
        physxFollowLookCameraUpHillGroundPitch,
        physxFollowLookCameraVelocityBlendTimeConstant,
        PhysxSchemaJointStateAPI,
        PhysxSchemaPhysxArticulationAPI,
        PhysxSchemaPhysxCameraAPI,
        PhysxSchemaPhysxCameraDroneAPI,
        PhysxSchemaPhysxCameraFollowAPI,
        PhysxSchemaPhysxCameraFollowLookAPI,
        PhysxSchemaPhysxCameraFollowVelocityAPI
    })
{
}

TfStaticData<UsdPhysXTokensType> UsdPhysXTokens;

PXR_NAMESPACE_CLOSE_SCOPE
