//
// Copyright 2016 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
#include "pxr/usd/usdPhysX/tokens.h"

PXR_NAMESPACE_OPEN_SCOPE

UsdPhysXTokensType::UsdPhysXTokensType() :
    acceleration("acceleration", TfToken::Immortal),
    alwaysUpdateEnabled("alwaysUpdateEnabled", TfToken::Immortal),
    Asynchronous("Asynchronous", TfToken::Immortal),
    average("average", TfToken::Immortal),
    constrained("constrained", TfToken::Immortal),
    Disabled("Disabled", TfToken::Immortal),
    easy("easy", TfToken::Immortal),
    force("force", TfToken::Immortal),
    GPU("GPU", TfToken::Immortal),
    hinge("hinge", TfToken::Immortal),
    hinge0("hinge0", TfToken::Immortal),
    hinge1("hinge1", TfToken::Immortal),
    jointState("jointState", TfToken::Immortal),
    jointState_MultipleApplyTemplate_PhysicsPosition("jointState:__INSTANCE_NAME__:physics:position", TfToken::Immortal),
    jointState_MultipleApplyTemplate_PhysicsVelocity("jointState:__INSTANCE_NAME__:physics:velocity", TfToken::Immortal),
    max("max", TfToken::Immortal),
    MBP("MBP", TfToken::Immortal),
    min("min", TfToken::Immortal),
    multiply("multiply", TfToken::Immortal),
    patch("patch", TfToken::Immortal),
    PCM("PCM", TfToken::Immortal),
    PGS("PGS", TfToken::Immortal),
    physicsBody0Indices("physics:body0Indices", TfToken::Immortal),
    physicsBody0s("physicsBody0s", TfToken::Immortal),
    physicsBody1Indices("physics:body1Indices", TfToken::Immortal),
    physicsBody1s("physicsBody1s", TfToken::Immortal),
    physicsGearRatio("physics:gearRatio", TfToken::Immortal),
    physicsLocalPos0s("physics:localPos0s", TfToken::Immortal),
    physicsLocalPos1s("physics:localPos1s", TfToken::Immortal),
    physicsLocalRot0s("physics:localRot0s", TfToken::Immortal),
    physicsLocalRot1s("physics:localRot1s", TfToken::Immortal),
    physicsProtoIndices("physics:protoIndices", TfToken::Immortal),
    physicsRatio("physics:ratio", TfToken::Immortal),
    physxArticulationArticulationEnabled("physxArticulation:articulationEnabled", TfToken::Immortal),
    physxArticulationEnabledSelfCollisions("physxArticulation:enabledSelfCollisions", TfToken::Immortal),
    physxArticulationSleepThreshold("physxArticulation:sleepThreshold", TfToken::Immortal),
    physxArticulationSolverPositionIterationCount("physxArticulation:solverPositionIterationCount", TfToken::Immortal),
    physxArticulationSolverVelocityIterationCount("physxArticulation:solverVelocityIterationCount", TfToken::Immortal),
    physxArticulationStabilizationThreshold("physxArticulation:stabilizationThreshold", TfToken::Immortal),
    physxCharacterControllerClimbingMode("physxCharacterController:climbingMode", TfToken::Immortal),
    physxCharacterControllerContactOffset("physxCharacterController:contactOffset", TfToken::Immortal),
    physxCharacterControllerInvisibleWallHeight("physxCharacterController:invisibleWallHeight", TfToken::Immortal),
    physxCharacterControllerMaxJumpHeight("physxCharacterController:maxJumpHeight", TfToken::Immortal),
    physxCharacterControllerMoveTarget("physxCharacterController:moveTarget", TfToken::Immortal),
    physxCharacterControllerNonWalkableMode("physxCharacterController:nonWalkableMode", TfToken::Immortal),
    physxCharacterControllerScaleCoeff("physxCharacterController:scaleCoeff", TfToken::Immortal),
    physxCharacterControllerSlopeLimit("physxCharacterController:slopeLimit", TfToken::Immortal),
    physxCharacterControllerStepOffset("physxCharacterController:stepOffset", TfToken::Immortal),
    physxCharacterControllerUpAxis("physxCharacterController:upAxis", TfToken::Immortal),
    physxCharacterControllerVolumeGrowth("physxCharacterController:volumeGrowth", TfToken::Immortal),
    physxCollisionContactOffset("physxCollision:contactOffset", TfToken::Immortal),
    physxCollisionMinTorsionalPatchRadius("physxCollision:minTorsionalPatchRadius", TfToken::Immortal),
    physxCollisionRestOffset("physxCollision:restOffset", TfToken::Immortal),
    physxCollisionTorsionalPatchRadius("physxCollision:torsionalPatchRadius", TfToken::Immortal),
    physxContactReportThreshold("physxContactReport:threshold", TfToken::Immortal),
    physxConvexDecompositionCollisionErrorPercentage("physxConvexDecompositionCollision:errorPercentage", TfToken::Immortal),
    physxConvexDecompositionCollisionHullVertexLimit("physxConvexDecompositionCollision:hullVertexLimit", TfToken::Immortal),
    physxConvexDecompositionCollisionMaxConvexHulls("physxConvexDecompositionCollision:maxConvexHulls", TfToken::Immortal),
    physxConvexDecompositionCollisionMinThickness("physxConvexDecompositionCollision:minThickness", TfToken::Immortal),
    physxConvexDecompositionCollisionShrinkWrap("physxConvexDecompositionCollision:shrinkWrap", TfToken::Immortal),
    physxConvexDecompositionCollisionVoxelResolution("physxConvexDecompositionCollision:voxelResolution", TfToken::Immortal),
    physxConvexHullCollisionHullVertexLimit("physxConvexHullCollision:hullVertexLimit", TfToken::Immortal),
    physxConvexHullCollisionMinThickness("physxConvexHullCollision:minThickness", TfToken::Immortal),
    physxCookedData("physxCookedData", TfToken::Immortal),
    physxCookedData_MultipleApplyTemplate_Buffer("physxCookedData:__INSTANCE_NAME__:buffer", TfToken::Immortal),
    physxDroneCameraFeedForwardVelocityGain("physxDroneCamera:feedForwardVelocityGain", TfToken::Immortal),
    physxDroneCameraFollowDistance("physxDroneCamera:followDistance", TfToken::Immortal),
    physxDroneCameraFollowHeight("physxDroneCamera:followHeight", TfToken::Immortal),
    physxDroneCameraHorizontalVelocityGain("physxDroneCamera:horizontalVelocityGain", TfToken::Immortal),
    physxDroneCameraMaxDistance("physxDroneCamera:maxDistance", TfToken::Immortal),
    physxDroneCameraMaxSpeed("physxDroneCamera:maxSpeed", TfToken::Immortal),
    physxDroneCameraPositionOffset("physxDroneCamera:positionOffset", TfToken::Immortal),
    physxDroneCameraRotationFilterTimeConstant("physxDroneCamera:rotationFilterTimeConstant", TfToken::Immortal),
    physxDroneCameraVelocityFilterTimeConstant("physxDroneCamera:velocityFilterTimeConstant", TfToken::Immortal),
    physxDroneCameraVerticalVelocityGain("physxDroneCamera:verticalVelocityGain", TfToken::Immortal),
    physxFollowCameraCameraPositionTimeConstant("physxFollowCamera:cameraPositionTimeConstant", TfToken::Immortal),
    physxFollowCameraFollowMaxDistance("physxFollowCamera:followMaxDistance", TfToken::Immortal),
    physxFollowCameraFollowMaxSpeed("physxFollowCamera:followMaxSpeed", TfToken::Immortal),
    physxFollowCameraFollowMinDistance("physxFollowCamera:followMinDistance", TfToken::Immortal),
    physxFollowCameraFollowMinSpeed("physxFollowCamera:followMinSpeed", TfToken::Immortal),
    physxFollowCameraFollowTurnRateGain("physxFollowCamera:followTurnRateGain", TfToken::Immortal),
    physxFollowCameraLookAheadMaxSpeed("physxFollowCamera:lookAheadMaxSpeed", TfToken::Immortal),
    physxFollowCameraLookAheadMinDistance("physxFollowCamera:lookAheadMinDistance", TfToken::Immortal),
    physxFollowCameraLookAheadMinSpeed("physxFollowCamera:lookAheadMinSpeed", TfToken::Immortal),
    physxFollowCameraLookAheadTurnRateGain("physxFollowCamera:lookAheadTurnRateGain", TfToken::Immortal),
    physxFollowCameraLookPositionHeight("physxFollowCamera:lookPositionHeight", TfToken::Immortal),
    physxFollowCameraLookPositionTimeConstant("physxFollowCamera:lookPositionTimeConstant", TfToken::Immortal),
    physxFollowCameraPitchAngle("physxFollowCamera:pitchAngle", TfToken::Immortal),
    physxFollowCameraPitchAngleTimeConstant("physxFollowCamera:pitchAngleTimeConstant", TfToken::Immortal),
    physxFollowCameraPositionOffset("physxFollowCamera:positionOffset", TfToken::Immortal),
    physxFollowCameraSlowPitchAngleSpeed("physxFollowCamera:slowPitchAngleSpeed", TfToken::Immortal),
    physxFollowCameraSlowSpeedPitchAngleScale("physxFollowCamera:slowSpeedPitchAngleScale", TfToken::Immortal),
    physxFollowCameraVelocityNormalMinSpeed("physxFollowCamera:velocityNormalMinSpeed", TfToken::Immortal),
    physxFollowCameraYawAngle("physxFollowCamera:yawAngle", TfToken::Immortal),
    physxFollowCameraYawRateTimeConstant("physxFollowCamera:yawRateTimeConstant", TfToken::Immortal),
    physxFollowFollowCameraLookAheadMaxDistance("physxFollowFollowCamera:lookAheadMaxDistance", TfToken::Immortal),
    physxFollowLookCameraDownHillGroundAngle("physxFollowLookCamera:downHillGroundAngle", TfToken::Immortal),
    physxFollowLookCameraDownHillGroundPitch("physxFollowLookCamera:downHillGroundPitch", TfToken::Immortal),
    physxFollowLookCameraFollowReverseDistance("physxFollowLookCamera:followReverseDistance", TfToken::Immortal),
    physxFollowLookCameraFollowReverseSpeed("physxFollowLookCamera:followReverseSpeed", TfToken::Immortal),
    physxFollowLookCameraUpHillGroundAngle("physxFollowLookCamera:upHillGroundAngle", TfToken::Immortal),
    physxFollowLookCameraUpHillGroundPitch("physxFollowLookCamera:upHillGroundPitch", TfToken::Immortal),
    physxFollowLookCameraVelocityBlendTimeConstant("physxFollowLookCamera:velocityBlendTimeConstant", TfToken::Immortal),
    physxForceForce("physxForce:force", TfToken::Immortal),
    physxForceForceEnabled("physxForce:forceEnabled", TfToken::Immortal),
    physxForceMode("physxForce:mode", TfToken::Immortal),
    physxForceTorque("physxForce:torque", TfToken::Immortal),
    physxForceWorldFrameEnabled("physxForce:worldFrameEnabled", TfToken::Immortal),
    physxIsosurfaceAnisotropyMax("physxIsosurface:anisotropyMax", TfToken::Immortal),
    physxIsosurfaceAnisotropyMin("physxIsosurface:anisotropyMin", TfToken::Immortal),
    physxIsosurfaceAnisotropyRadius("physxIsosurface:anisotropyRadius", TfToken::Immortal),
    physxIsosurfaceEnableAnisotropy("physxIsosurface:enableAnisotropy", TfToken::Immortal),
    physxIsosurfaceGridFilteringPasses("physxIsosurface:gridFilteringPasses", TfToken::Immortal),
    physxIsosurfaceGridSmoothingRadiusRelativeToCellSize("physxIsosurface:gridSmoothingRadiusRelativeToCellSize", TfToken::Immortal),
    physxIsosurfaceGridSpacing("physxIsosurface:gridSpacing", TfToken::Immortal),
    physxIsosurfaceIsoSurfaceEnabled("physxIsosurface:isoSurfaceEnabled", TfToken::Immortal),
    physxIsosurfaceIsosurfaceLevel("physxIsosurface:isosurfaceLevel", TfToken::Immortal),
    physxIsosurfaceKernelRadius("physxIsosurface:kernelRadius", TfToken::Immortal),
    physxIsosurfaceMaxSubgrids("physxIsosurface:maxSubgrids", TfToken::Immortal),
    physxIsosurfaceMaxTriangles("physxIsosurface:maxTriangles", TfToken::Immortal),
    physxIsosurfaceMaxVertices("physxIsosurface:maxVertices", TfToken::Immortal),
    physxIsosurfaceNumMeshSmoothingPasses("physxIsosurface:numMeshSmoothingPasses", TfToken::Immortal),
    physxJointArmature("physxJoint:armature", TfToken::Immortal),
    physxJointEnableProjection("physxJoint:enableProjection", TfToken::Immortal),
    physxJointJointFriction("physxJoint:jointFriction", TfToken::Immortal),
    physxJointMaxJointVelocity("physxJoint:maxJointVelocity", TfToken::Immortal),
    physxMaterialCompliantContactAccelerationSpring("physxMaterial:compliantContactAccelerationSpring", TfToken::Immortal),
    physxMaterialCompliantContactDamping("physxMaterial:compliantContactDamping", TfToken::Immortal),
    physxMaterialCompliantContactStiffness("physxMaterial:compliantContactStiffness", TfToken::Immortal),
    physxMaterialDampingCombineMode("physxMaterial:dampingCombineMode", TfToken::Immortal),
    physxMaterialFrictionCombineMode("physxMaterial:frictionCombineMode", TfToken::Immortal),
    physxMaterialRestitutionCombineMode("physxMaterial:restitutionCombineMode", TfToken::Immortal),
    physxMimicJoint("physxMimicJoint", TfToken::Immortal),
    physxMimicJoint_MultipleApplyTemplate_Gearing("physxMimicJoint:__INSTANCE_NAME__:gearing", TfToken::Immortal),
    physxMimicJoint_MultipleApplyTemplate_Offset("physxMimicJoint:__INSTANCE_NAME__:offset", TfToken::Immortal),
    physxMimicJoint_MultipleApplyTemplate_ReferenceJointAxis("physxMimicJoint:__INSTANCE_NAME__:referenceJointAxis", TfToken::Immortal),
    physxPhysicsDistanceJointSpringDamping("physxPhysicsDistanceJoint:springDamping", TfToken::Immortal),
    physxPhysicsDistanceJointSpringEnabled("physxPhysicsDistanceJoint:springEnabled", TfToken::Immortal),
    physxPhysicsDistanceJointSpringStiffness("physxPhysicsDistanceJoint:springStiffness", TfToken::Immortal),
    physxResidualReportingMaxResidualPositionIteration("physxResidualReporting:maxResidualPositionIteration", TfToken::Immortal),
    physxResidualReportingMaxResidualVelocityIteration("physxResidualReporting:maxResidualVelocityIteration", TfToken::Immortal),
    physxResidualReportingRmsResidualPositionIteration("physxResidualReporting:rmsResidualPositionIteration", TfToken::Immortal),
    physxResidualReportingRmsResidualVelocityIteration("physxResidualReporting:rmsResidualVelocityIteration", TfToken::Immortal),
    physxRigidBodyAngularDamping("physxRigidBody:angularDamping", TfToken::Immortal),
    physxRigidBodyCfmScale("physxRigidBody:cfmScale", TfToken::Immortal),
    physxRigidBodyContactSlopCoefficient("physxRigidBody:contactSlopCoefficient", TfToken::Immortal),
    physxRigidBodyDisableGravity("physxRigidBody:disableGravity", TfToken::Immortal),
    physxRigidBodyEnableCCD("physxRigidBody:enableCCD", TfToken::Immortal),
    physxRigidBodyEnableGyroscopicForces("physxRigidBody:enableGyroscopicForces", TfToken::Immortal),
    physxRigidBodyEnableSpeculativeCCD("physxRigidBody:enableSpeculativeCCD", TfToken::Immortal),
    physxRigidBodyLinearDamping("physxRigidBody:linearDamping", TfToken::Immortal),
    physxRigidBodyLockedPosAxis("physxRigidBody:lockedPosAxis", TfToken::Immortal),
    physxRigidBodyLockedRotAxis("physxRigidBody:lockedRotAxis", TfToken::Immortal),
    physxRigidBodyMaxAngularVelocity("physxRigidBody:maxAngularVelocity", TfToken::Immortal),
    physxRigidBodyMaxContactImpulse("physxRigidBody:maxContactImpulse", TfToken::Immortal),
    physxRigidBodyMaxDepenetrationVelocity("physxRigidBody:maxDepenetrationVelocity", TfToken::Immortal),
    physxRigidBodyMaxLinearVelocity("physxRigidBody:maxLinearVelocity", TfToken::Immortal),
    physxRigidBodyRetainAccelerations("physxRigidBody:retainAccelerations", TfToken::Immortal),
    physxRigidBodySleepThreshold("physxRigidBody:sleepThreshold", TfToken::Immortal),
    physxRigidBodySolveContact("physxRigidBody:solveContact", TfToken::Immortal),
    physxRigidBodySolverPositionIterationCount("physxRigidBody:solverPositionIterationCount", TfToken::Immortal),
    physxRigidBodySolverVelocityIterationCount("physxRigidBody:solverVelocityIterationCount", TfToken::Immortal),
    physxRigidBodyStabilizationThreshold("physxRigidBody:stabilizationThreshold", TfToken::Immortal),
    physxSceneBounceThreshold("physxScene:bounceThreshold", TfToken::Immortal),
    physxSceneBroadphaseType("physxScene:broadphaseType", TfToken::Immortal),
    physxSceneCollisionSystem("physxScene:collisionSystem", TfToken::Immortal),
    physxSceneEnableCCD("physxScene:enableCCD", TfToken::Immortal),
    physxSceneEnableEnhancedDeterminism("physxScene:enableEnhancedDeterminism", TfToken::Immortal),
    physxSceneEnableExternalForcesEveryIteration("physxScene:enableExternalForcesEveryIteration", TfToken::Immortal),
    physxSceneEnableGPUDynamics("physxScene:enableGPUDynamics", TfToken::Immortal),
    physxSceneEnableResidualReporting("physxScene:enableResidualReporting", TfToken::Immortal),
    physxSceneEnableSceneQuerySupport("physxScene:enableSceneQuerySupport", TfToken::Immortal),
    physxSceneEnableStabilization("physxScene:enableStabilization", TfToken::Immortal),
    physxSceneFrictionCorrelationDistance("physxScene:frictionCorrelationDistance", TfToken::Immortal),
    physxSceneFrictionOffsetThreshold("physxScene:frictionOffsetThreshold", TfToken::Immortal),
    physxSceneFrictionType("physxScene:frictionType", TfToken::Immortal),
    physxSceneGpuCollisionStackSize("physxScene:gpuCollisionStackSize", TfToken::Immortal),
    physxSceneGpuFoundLostAggregatePairsCapacity("physxScene:gpuFoundLostAggregatePairsCapacity", TfToken::Immortal),
    physxSceneGpuFoundLostPairsCapacity("physxScene:gpuFoundLostPairsCapacity", TfToken::Immortal),
    physxSceneGpuHeapCapacity("physxScene:gpuHeapCapacity", TfToken::Immortal),
    physxSceneGpuMaxDeformableSurfaceContacts("physxScene:gpuMaxDeformableSurfaceContacts", TfToken::Immortal),
    physxSceneGpuMaxHairContacts("physxScene:gpuMaxHairContacts", TfToken::Immortal),
    physxSceneGpuMaxNumPartitions("physxScene:gpuMaxNumPartitions", TfToken::Immortal),
    physxSceneGpuMaxParticleContacts("physxScene:gpuMaxParticleContacts", TfToken::Immortal),
    physxSceneGpuMaxRigidContactCount("physxScene:gpuMaxRigidContactCount", TfToken::Immortal),
    physxSceneGpuMaxRigidPatchCount("physxScene:gpuMaxRigidPatchCount", TfToken::Immortal),
    physxSceneGpuMaxSoftBodyContacts("physxScene:gpuMaxSoftBodyContacts", TfToken::Immortal),
    physxSceneGpuTempBufferCapacity("physxScene:gpuTempBufferCapacity", TfToken::Immortal),
    physxSceneGpuTotalAggregatePairsCapacity("physxScene:gpuTotalAggregatePairsCapacity", TfToken::Immortal),
    physxSceneInvertCollisionGroupFilter("physxScene:invertCollisionGroupFilter", TfToken::Immortal),
    physxSceneMaxBiasCoefficient("physxScene:maxBiasCoefficient", TfToken::Immortal),
    physxSceneMaxPositionIterationCount("physxScene:maxPositionIterationCount", TfToken::Immortal),
    physxSceneMaxVelocityIterationCount("physxScene:maxVelocityIterationCount", TfToken::Immortal),
    physxSceneMinPositionIterationCount("physxScene:minPositionIterationCount", TfToken::Immortal),
    physxSceneMinVelocityIterationCount("physxScene:minVelocityIterationCount", TfToken::Immortal),
    physxSceneReportKinematicKinematicPairs("physxScene:reportKinematicKinematicPairs", TfToken::Immortal),
    physxSceneReportKinematicStaticPairs("physxScene:reportKinematicStaticPairs", TfToken::Immortal),
    physxSceneSolverType("physxScene:solverType", TfToken::Immortal),
    physxSceneTimeStepsPerSecond("physxScene:timeStepsPerSecond", TfToken::Immortal),
    physxSceneUpdateType("physxScene:updateType", TfToken::Immortal),
    preventClimbing("preventClimbing", TfToken::Immortal),
    preventClimbingForceSliding("preventClimbingForceSliding", TfToken::Immortal),
    prismatic("prismatic", TfToken::Immortal),
    rotX("rotX", TfToken::Immortal),
    rotY("rotY", TfToken::Immortal),
    rotZ("rotZ", TfToken::Immortal),
    SAP("SAP", TfToken::Immortal),
    SAT("SAT", TfToken::Immortal),
    Synchronous("Synchronous", TfToken::Immortal),
    TGS("TGS", TfToken::Immortal),
    X("X", TfToken::Immortal),
    Y("Y", TfToken::Immortal),
    Z("Z", TfToken::Immortal),
    PhysxSchemaJointStateAPI("PhysxSchemaJointStateAPI", TfToken::Immortal),
    PhysxSchemaPhysxArticulationAPI("PhysxSchemaPhysxArticulationAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraAPI("PhysxSchemaPhysxCameraAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraDroneAPI("PhysxSchemaPhysxCameraDroneAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowAPI("PhysxSchemaPhysxCameraFollowAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowLookAPI("PhysxSchemaPhysxCameraFollowLookAPI", TfToken::Immortal),
    PhysxSchemaPhysxCameraFollowVelocityAPI("PhysxSchemaPhysxCameraFollowVelocityAPI", TfToken::Immortal),
    PhysxSchemaPhysxCharacterControllerAPI("PhysxSchemaPhysxCharacterControllerAPI", TfToken::Immortal),
    PhysxSchemaPhysxCollisionAPI("PhysxSchemaPhysxCollisionAPI", TfToken::Immortal),
    PhysxSchemaPhysxContactReportAPI("PhysxSchemaPhysxContactReportAPI", TfToken::Immortal),
    PhysxSchemaPhysxConvexDecompositionCollisionAPI("PhysxSchemaPhysxConvexDecompositionCollisionAPI", TfToken::Immortal),
    PhysxSchemaPhysxConvexHullCollisionAPI("PhysxSchemaPhysxConvexHullCollisionAPI", TfToken::Immortal),
    PhysxSchemaPhysxCookedDataAPI("PhysxSchemaPhysxCookedDataAPI", TfToken::Immortal),
    PhysxSchemaPhysxForceAPI("PhysxSchemaPhysxForceAPI", TfToken::Immortal),
    PhysxSchemaPhysxIsosurfaceAPI("PhysxSchemaPhysxIsosurfaceAPI", TfToken::Immortal),
    PhysxSchemaPhysxJointAPI("PhysxSchemaPhysxJointAPI", TfToken::Immortal),
    PhysxSchemaPhysxMaterialAPI("PhysxSchemaPhysxMaterialAPI", TfToken::Immortal),
    PhysxSchemaPhysxMeshMergeCollisionAPI("PhysxSchemaPhysxMeshMergeCollisionAPI", TfToken::Immortal),
    PhysxSchemaPhysxMimicJointAPI("PhysxSchemaPhysxMimicJointAPI", TfToken::Immortal),
    PhysxSchemaPhysxPhysicsDistanceJointAPI("PhysxSchemaPhysxPhysicsDistanceJointAPI", TfToken::Immortal),
    PhysxSchemaPhysxPhysicsGearJoint("PhysxSchemaPhysxPhysicsGearJoint", TfToken::Immortal),
    PhysxSchemaPhysxPhysicsInstancer("PhysxSchemaPhysxPhysicsInstancer", TfToken::Immortal),
    PhysxSchemaPhysxPhysicsJointInstancer("PhysxSchemaPhysxPhysicsJointInstancer", TfToken::Immortal),
    PhysxSchemaPhysxPhysicsRackAndPinionJoint("PhysxSchemaPhysxPhysicsRackAndPinionJoint", TfToken::Immortal),
    PhysxSchemaPhysxResidualReportingAPI("PhysxSchemaPhysxResidualReportingAPI", TfToken::Immortal),
    PhysxSchemaPhysxRigidBodyAPI("PhysxSchemaPhysxRigidBodyAPI", TfToken::Immortal),
    PhysxSchemaPhysxSceneAPI("PhysxSchemaPhysxSceneAPI", TfToken::Immortal),
    allTokens({
        acceleration,
        alwaysUpdateEnabled,
        Asynchronous,
        average,
        constrained,
        Disabled,
        easy,
        force,
        GPU,
        hinge,
        hinge0,
        hinge1,
        jointState,
        jointState_MultipleApplyTemplate_PhysicsPosition,
        jointState_MultipleApplyTemplate_PhysicsVelocity,
        max,
        MBP,
        min,
        multiply,
        patch,
        PCM,
        PGS,
        physicsBody0Indices,
        physicsBody0s,
        physicsBody1Indices,
        physicsBody1s,
        physicsGearRatio,
        physicsLocalPos0s,
        physicsLocalPos1s,
        physicsLocalRot0s,
        physicsLocalRot1s,
        physicsProtoIndices,
        physicsRatio,
        physxArticulationArticulationEnabled,
        physxArticulationEnabledSelfCollisions,
        physxArticulationSleepThreshold,
        physxArticulationSolverPositionIterationCount,
        physxArticulationSolverVelocityIterationCount,
        physxArticulationStabilizationThreshold,
        physxCharacterControllerClimbingMode,
        physxCharacterControllerContactOffset,
        physxCharacterControllerInvisibleWallHeight,
        physxCharacterControllerMaxJumpHeight,
        physxCharacterControllerMoveTarget,
        physxCharacterControllerNonWalkableMode,
        physxCharacterControllerScaleCoeff,
        physxCharacterControllerSlopeLimit,
        physxCharacterControllerStepOffset,
        physxCharacterControllerUpAxis,
        physxCharacterControllerVolumeGrowth,
        physxCollisionContactOffset,
        physxCollisionMinTorsionalPatchRadius,
        physxCollisionRestOffset,
        physxCollisionTorsionalPatchRadius,
        physxContactReportThreshold,
        physxConvexDecompositionCollisionErrorPercentage,
        physxConvexDecompositionCollisionHullVertexLimit,
        physxConvexDecompositionCollisionMaxConvexHulls,
        physxConvexDecompositionCollisionMinThickness,
        physxConvexDecompositionCollisionShrinkWrap,
        physxConvexDecompositionCollisionVoxelResolution,
        physxConvexHullCollisionHullVertexLimit,
        physxConvexHullCollisionMinThickness,
        physxCookedData,
        physxCookedData_MultipleApplyTemplate_Buffer,
        physxDroneCameraFeedForwardVelocityGain,
        physxDroneCameraFollowDistance,
        physxDroneCameraFollowHeight,
        physxDroneCameraHorizontalVelocityGain,
        physxDroneCameraMaxDistance,
        physxDroneCameraMaxSpeed,
        physxDroneCameraPositionOffset,
        physxDroneCameraRotationFilterTimeConstant,
        physxDroneCameraVelocityFilterTimeConstant,
        physxDroneCameraVerticalVelocityGain,
        physxFollowCameraCameraPositionTimeConstant,
        physxFollowCameraFollowMaxDistance,
        physxFollowCameraFollowMaxSpeed,
        physxFollowCameraFollowMinDistance,
        physxFollowCameraFollowMinSpeed,
        physxFollowCameraFollowTurnRateGain,
        physxFollowCameraLookAheadMaxSpeed,
        physxFollowCameraLookAheadMinDistance,
        physxFollowCameraLookAheadMinSpeed,
        physxFollowCameraLookAheadTurnRateGain,
        physxFollowCameraLookPositionHeight,
        physxFollowCameraLookPositionTimeConstant,
        physxFollowCameraPitchAngle,
        physxFollowCameraPitchAngleTimeConstant,
        physxFollowCameraPositionOffset,
        physxFollowCameraSlowPitchAngleSpeed,
        physxFollowCameraSlowSpeedPitchAngleScale,
        physxFollowCameraVelocityNormalMinSpeed,
        physxFollowCameraYawAngle,
        physxFollowCameraYawRateTimeConstant,
        physxFollowFollowCameraLookAheadMaxDistance,
        physxFollowLookCameraDownHillGroundAngle,
        physxFollowLookCameraDownHillGroundPitch,
        physxFollowLookCameraFollowReverseDistance,
        physxFollowLookCameraFollowReverseSpeed,
        physxFollowLookCameraUpHillGroundAngle,
        physxFollowLookCameraUpHillGroundPitch,
        physxFollowLookCameraVelocityBlendTimeConstant,
        physxForceForce,
        physxForceForceEnabled,
        physxForceMode,
        physxForceTorque,
        physxForceWorldFrameEnabled,
        physxIsosurfaceAnisotropyMax,
        physxIsosurfaceAnisotropyMin,
        physxIsosurfaceAnisotropyRadius,
        physxIsosurfaceEnableAnisotropy,
        physxIsosurfaceGridFilteringPasses,
        physxIsosurfaceGridSmoothingRadiusRelativeToCellSize,
        physxIsosurfaceGridSpacing,
        physxIsosurfaceIsoSurfaceEnabled,
        physxIsosurfaceIsosurfaceLevel,
        physxIsosurfaceKernelRadius,
        physxIsosurfaceMaxSubgrids,
        physxIsosurfaceMaxTriangles,
        physxIsosurfaceMaxVertices,
        physxIsosurfaceNumMeshSmoothingPasses,
        physxJointArmature,
        physxJointEnableProjection,
        physxJointJointFriction,
        physxJointMaxJointVelocity,
        physxMaterialCompliantContactAccelerationSpring,
        physxMaterialCompliantContactDamping,
        physxMaterialCompliantContactStiffness,
        physxMaterialDampingCombineMode,
        physxMaterialFrictionCombineMode,
        physxMaterialRestitutionCombineMode,
        physxMimicJoint,
        physxMimicJoint_MultipleApplyTemplate_Gearing,
        physxMimicJoint_MultipleApplyTemplate_Offset,
        physxMimicJoint_MultipleApplyTemplate_ReferenceJointAxis,
        physxPhysicsDistanceJointSpringDamping,
        physxPhysicsDistanceJointSpringEnabled,
        physxPhysicsDistanceJointSpringStiffness,
        physxResidualReportingMaxResidualPositionIteration,
        physxResidualReportingMaxResidualVelocityIteration,
        physxResidualReportingRmsResidualPositionIteration,
        physxResidualReportingRmsResidualVelocityIteration,
        physxRigidBodyAngularDamping,
        physxRigidBodyCfmScale,
        physxRigidBodyContactSlopCoefficient,
        physxRigidBodyDisableGravity,
        physxRigidBodyEnableCCD,
        physxRigidBodyEnableGyroscopicForces,
        physxRigidBodyEnableSpeculativeCCD,
        physxRigidBodyLinearDamping,
        physxRigidBodyLockedPosAxis,
        physxRigidBodyLockedRotAxis,
        physxRigidBodyMaxAngularVelocity,
        physxRigidBodyMaxContactImpulse,
        physxRigidBodyMaxDepenetrationVelocity,
        physxRigidBodyMaxLinearVelocity,
        physxRigidBodyRetainAccelerations,
        physxRigidBodySleepThreshold,
        physxRigidBodySolveContact,
        physxRigidBodySolverPositionIterationCount,
        physxRigidBodySolverVelocityIterationCount,
        physxRigidBodyStabilizationThreshold,
        physxSceneBounceThreshold,
        physxSceneBroadphaseType,
        physxSceneCollisionSystem,
        physxSceneEnableCCD,
        physxSceneEnableEnhancedDeterminism,
        physxSceneEnableExternalForcesEveryIteration,
        physxSceneEnableGPUDynamics,
        physxSceneEnableResidualReporting,
        physxSceneEnableSceneQuerySupport,
        physxSceneEnableStabilization,
        physxSceneFrictionCorrelationDistance,
        physxSceneFrictionOffsetThreshold,
        physxSceneFrictionType,
        physxSceneGpuCollisionStackSize,
        physxSceneGpuFoundLostAggregatePairsCapacity,
        physxSceneGpuFoundLostPairsCapacity,
        physxSceneGpuHeapCapacity,
        physxSceneGpuMaxDeformableSurfaceContacts,
        physxSceneGpuMaxHairContacts,
        physxSceneGpuMaxNumPartitions,
        physxSceneGpuMaxParticleContacts,
        physxSceneGpuMaxRigidContactCount,
        physxSceneGpuMaxRigidPatchCount,
        physxSceneGpuMaxSoftBodyContacts,
        physxSceneGpuTempBufferCapacity,
        physxSceneGpuTotalAggregatePairsCapacity,
        physxSceneInvertCollisionGroupFilter,
        physxSceneMaxBiasCoefficient,
        physxSceneMaxPositionIterationCount,
        physxSceneMaxVelocityIterationCount,
        physxSceneMinPositionIterationCount,
        physxSceneMinVelocityIterationCount,
        physxSceneReportKinematicKinematicPairs,
        physxSceneReportKinematicStaticPairs,
        physxSceneSolverType,
        physxSceneTimeStepsPerSecond,
        physxSceneUpdateType,
        preventClimbing,
        preventClimbingForceSliding,
        prismatic,
        rotX,
        rotY,
        rotZ,
        SAP,
        SAT,
        Synchronous,
        TGS,
        X,
        Y,
        Z,
        PhysxSchemaJointStateAPI,
        PhysxSchemaPhysxArticulationAPI,
        PhysxSchemaPhysxCameraAPI,
        PhysxSchemaPhysxCameraDroneAPI,
        PhysxSchemaPhysxCameraFollowAPI,
        PhysxSchemaPhysxCameraFollowLookAPI,
        PhysxSchemaPhysxCameraFollowVelocityAPI,
        PhysxSchemaPhysxCharacterControllerAPI,
        PhysxSchemaPhysxCollisionAPI,
        PhysxSchemaPhysxContactReportAPI,
        PhysxSchemaPhysxConvexDecompositionCollisionAPI,
        PhysxSchemaPhysxConvexHullCollisionAPI,
        PhysxSchemaPhysxCookedDataAPI,
        PhysxSchemaPhysxForceAPI,
        PhysxSchemaPhysxIsosurfaceAPI,
        PhysxSchemaPhysxJointAPI,
        PhysxSchemaPhysxMaterialAPI,
        PhysxSchemaPhysxMeshMergeCollisionAPI,
        PhysxSchemaPhysxMimicJointAPI,
        PhysxSchemaPhysxPhysicsDistanceJointAPI,
        PhysxSchemaPhysxPhysicsGearJoint,
        PhysxSchemaPhysxPhysicsInstancer,
        PhysxSchemaPhysxPhysicsJointInstancer,
        PhysxSchemaPhysxPhysicsRackAndPinionJoint,
        PhysxSchemaPhysxResidualReportingAPI,
        PhysxSchemaPhysxRigidBodyAPI,
        PhysxSchemaPhysxSceneAPI
    })
{
}

TfStaticData<UsdPhysXTokensType> UsdPhysXTokens;

PXR_NAMESPACE_CLOSE_SCOPE
