//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/massSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingMassSchemaTokens,
    USD_PHYSICS_IMAGING_MASS_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
UsdPhysicsImagingMassSchema::GetMass() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingMassSchemaTokens->mass);
}

HdFloatDataSourceHandle
UsdPhysicsImagingMassSchema::GetDensity() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingMassSchemaTokens->density);
}

HdVec3fDataSourceHandle
UsdPhysicsImagingMassSchema::GetCenterOfMass() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        UsdPhysicsImagingMassSchemaTokens->centerOfMass);
}

HdVec3fDataSourceHandle
UsdPhysicsImagingMassSchema::GetDiagonalInertia() const
{
    return _GetTypedDataSource<HdVec3fDataSource>(
        UsdPhysicsImagingMassSchemaTokens->diagonalInertia);
}

HdQuatfDataSourceHandle
UsdPhysicsImagingMassSchema::GetPrincipalAxes() const
{
    return _GetTypedDataSource<HdQuatfDataSource>(
        UsdPhysicsImagingMassSchemaTokens->principalAxes);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingMassSchema::BuildRetained(
        const HdFloatDataSourceHandle &mass,
        const HdFloatDataSourceHandle &density,
        const HdVec3fDataSourceHandle &centerOfMass,
        const HdVec3fDataSourceHandle &diagonalInertia,
        const HdQuatfDataSourceHandle &principalAxes
)
{
    TfToken _names[5];
    HdDataSourceBaseHandle _values[5];

    size_t _count = 0;

    if (mass) {
        _names[_count] = UsdPhysicsImagingMassSchemaTokens->mass;
        _values[_count++] = mass;
    }

    if (density) {
        _names[_count] = UsdPhysicsImagingMassSchemaTokens->density;
        _values[_count++] = density;
    }

    if (centerOfMass) {
        _names[_count] = UsdPhysicsImagingMassSchemaTokens->centerOfMass;
        _values[_count++] = centerOfMass;
    }

    if (diagonalInertia) {
        _names[_count] = UsdPhysicsImagingMassSchemaTokens->diagonalInertia;
        _values[_count++] = diagonalInertia;
    }

    if (principalAxes) {
        _names[_count] = UsdPhysicsImagingMassSchemaTokens->principalAxes;
        _values[_count++] = principalAxes;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingMassSchema::Builder &
UsdPhysicsImagingMassSchema::Builder::SetMass(
    const HdFloatDataSourceHandle &mass)
{
    _mass = mass;
    return *this;
}

UsdPhysicsImagingMassSchema::Builder &
UsdPhysicsImagingMassSchema::Builder::SetDensity(
    const HdFloatDataSourceHandle &density)
{
    _density = density;
    return *this;
}

UsdPhysicsImagingMassSchema::Builder &
UsdPhysicsImagingMassSchema::Builder::SetCenterOfMass(
    const HdVec3fDataSourceHandle &centerOfMass)
{
    _centerOfMass = centerOfMass;
    return *this;
}

UsdPhysicsImagingMassSchema::Builder &
UsdPhysicsImagingMassSchema::Builder::SetDiagonalInertia(
    const HdVec3fDataSourceHandle &diagonalInertia)
{
    _diagonalInertia = diagonalInertia;
    return *this;
}

UsdPhysicsImagingMassSchema::Builder &
UsdPhysicsImagingMassSchema::Builder::SetPrincipalAxes(
    const HdQuatfDataSourceHandle &principalAxes)
{
    _principalAxes = principalAxes;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingMassSchema::Builder::Build()
{
    return UsdPhysicsImagingMassSchema::BuildRetained(
        _mass,
        _density,
        _centerOfMass,
        _diagonalInertia,
        _principalAxes
    );
}

/*static*/
UsdPhysicsImagingMassSchema
UsdPhysicsImagingMassSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingMassSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingMassSchemaTokens->mass))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingMassSchema::GetSchemaToken()
{
    return UsdPhysicsImagingMassSchemaTokens->mass;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetMassLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingMassSchemaTokens->mass);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetDensityLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingMassSchemaTokens->density);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetCenterOfMassLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingMassSchemaTokens->centerOfMass);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetDiagonalInertiaLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingMassSchemaTokens->diagonalInertia);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingMassSchema::GetPrincipalAxesLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingMassSchemaTokens->principalAxes);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE