//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxCameraFollowLookSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_CAMERA_FOLLOW_LOOK_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetDownHillGroundAngle() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundAngle);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetDownHillGroundPitch() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundPitch);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetFollowReverseDistance() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseDistance);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetFollowReverseSpeed() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseSpeed);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetUpHillGroundAngle() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundAngle);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetUpHillGroundPitch() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundPitch);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetVelocityBlendTimeConstant() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->velocityBlendTimeConstant);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::BuildRetained(
        const HdFloatDataSourceHandle &downHillGroundAngle,
        const HdFloatDataSourceHandle &downHillGroundPitch,
        const HdFloatDataSourceHandle &followReverseDistance,
        const HdFloatDataSourceHandle &followReverseSpeed,
        const HdFloatDataSourceHandle &upHillGroundAngle,
        const HdFloatDataSourceHandle &upHillGroundPitch,
        const HdFloatDataSourceHandle &velocityBlendTimeConstant
)
{
    TfToken _names[7];
    HdDataSourceBaseHandle _values[7];

    size_t _count = 0;

    if (downHillGroundAngle) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundAngle;
        _values[_count++] = downHillGroundAngle;
    }

    if (downHillGroundPitch) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundPitch;
        _values[_count++] = downHillGroundPitch;
    }

    if (followReverseDistance) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseDistance;
        _values[_count++] = followReverseDistance;
    }

    if (followReverseSpeed) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseSpeed;
        _values[_count++] = followReverseSpeed;
    }

    if (upHillGroundAngle) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundAngle;
        _values[_count++] = upHillGroundAngle;
    }

    if (upHillGroundPitch) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundPitch;
        _values[_count++] = upHillGroundPitch;
    }

    if (velocityBlendTimeConstant) {
        _names[_count] = UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->velocityBlendTimeConstant;
        _values[_count++] = velocityBlendTimeConstant;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetDownHillGroundAngle(
    const HdFloatDataSourceHandle &downHillGroundAngle)
{
    _downHillGroundAngle = downHillGroundAngle;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetDownHillGroundPitch(
    const HdFloatDataSourceHandle &downHillGroundPitch)
{
    _downHillGroundPitch = downHillGroundPitch;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetFollowReverseDistance(
    const HdFloatDataSourceHandle &followReverseDistance)
{
    _followReverseDistance = followReverseDistance;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetFollowReverseSpeed(
    const HdFloatDataSourceHandle &followReverseSpeed)
{
    _followReverseSpeed = followReverseSpeed;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetUpHillGroundAngle(
    const HdFloatDataSourceHandle &upHillGroundAngle)
{
    _upHillGroundAngle = upHillGroundAngle;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetUpHillGroundPitch(
    const HdFloatDataSourceHandle &upHillGroundPitch)
{
    _upHillGroundPitch = upHillGroundPitch;
    return *this;
}

UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder &
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::SetVelocityBlendTimeConstant(
    const HdFloatDataSourceHandle &velocityBlendTimeConstant)
{
    _velocityBlendTimeConstant = velocityBlendTimeConstant;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCameraFollowLookSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxCameraFollowLookSchema::BuildRetained(
        _downHillGroundAngle,
        _downHillGroundPitch,
        _followReverseDistance,
        _followReverseSpeed,
        _upHillGroundAngle,
        _upHillGroundPitch,
        _velocityBlendTimeConstant
    );
}

/*static*/
UsdPhysicsImagingPhysxCameraFollowLookSchema
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxCameraFollowLookSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->physxCameraFollowLook))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->physxCameraFollowLook;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetDownHillGroundAngleLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundAngle);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetDownHillGroundPitchLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->downHillGroundPitch);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetFollowReverseDistanceLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseDistance);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetFollowReverseSpeedLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->followReverseSpeed);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetUpHillGroundAngleLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundAngle);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetUpHillGroundPitchLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->upHillGroundPitch);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraFollowLookSchema::GetVelocityBlendTimeConstantLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraFollowLookSchemaTokens->velocityBlendTimeConstant);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE