//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxCookedDataSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxCookedDataSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_COOKED_DATA_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdIntArrayDataSourceHandle
UsdPhysicsImagingPhysxCookedDataSchema::GetBuffer() const
{
    return _GetTypedDataSource<HdIntArrayDataSource>(
        UsdPhysicsImagingPhysxCookedDataSchemaTokens->buffer);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCookedDataSchema::BuildRetained(
        const HdIntArrayDataSourceHandle &buffer
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (buffer) {
        _names[_count] = UsdPhysicsImagingPhysxCookedDataSchemaTokens->buffer;
        _values[_count++] = buffer;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxCookedDataSchema::Builder &
UsdPhysicsImagingPhysxCookedDataSchema::Builder::SetBuffer(
    const HdIntArrayDataSourceHandle &buffer)
{
    _buffer = buffer;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCookedDataSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxCookedDataSchema::BuildRetained(
        _buffer
    );
}

/*static*/
UsdPhysicsImagingPhysxCookedDataSchema
UsdPhysicsImagingPhysxCookedDataSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxCookedDataSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxCookedDataSchemaTokens->physxCookedData))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxCookedDataSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxCookedDataSchemaTokens->physxCookedData;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCookedDataSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCookedDataSchema::GetBufferLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCookedDataSchemaTokens->buffer);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE