//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxTriggerStateSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxTriggerStateSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_TRIGGER_STATE_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdPathArrayDataSourceHandle
UsdPhysicsImagingPhysxTriggerStateSchema::GetTriggeredCollisions() const
{
    return _GetTypedDataSource<HdPathArrayDataSource>(
        UsdPhysicsImagingPhysxTriggerStateSchemaTokens->triggeredCollisions);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxTriggerStateSchema::BuildRetained(
        const HdPathArrayDataSourceHandle &triggeredCollisions
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (triggeredCollisions) {
        _names[_count] = UsdPhysicsImagingPhysxTriggerStateSchemaTokens->triggeredCollisions;
        _values[_count++] = triggeredCollisions;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxTriggerStateSchema::Builder &
UsdPhysicsImagingPhysxTriggerStateSchema::Builder::SetTriggeredCollisions(
    const HdPathArrayDataSourceHandle &triggeredCollisions)
{
    _triggeredCollisions = triggeredCollisions;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxTriggerStateSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxTriggerStateSchema::BuildRetained(
        _triggeredCollisions
    );
}

/*static*/
UsdPhysicsImagingPhysxTriggerStateSchema
UsdPhysicsImagingPhysxTriggerStateSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxTriggerStateSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxTriggerStateSchemaTokens->physxTriggerState))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxTriggerStateSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxTriggerStateSchemaTokens->physxTriggerState;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxTriggerStateSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxTriggerStateSchema::GetTriggeredCollisionsLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxTriggerStateSchemaTokens->triggeredCollisions);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE