//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxSDFMeshCollisionSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_SDFMESH_COLLISION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfBitsPerSubgridPixel() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfBitsPerSubgridPixel);
}

HdBoolDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfEnableRemeshing() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfEnableRemeshing);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfMargin() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfMargin);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfNarrowBandThickness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfNarrowBandThickness);
}

HdIntDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfResolution() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfResolution);
}

HdIntDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfSubgridResolution() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfSubgridResolution);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfTriangleCountReductionFactor() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfTriangleCountReductionFactor);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::BuildRetained(
        const HdTokenDataSourceHandle &sdfBitsPerSubgridPixel,
        const HdBoolDataSourceHandle &sdfEnableRemeshing,
        const HdFloatDataSourceHandle &sdfMargin,
        const HdFloatDataSourceHandle &sdfNarrowBandThickness,
        const HdIntDataSourceHandle &sdfResolution,
        const HdIntDataSourceHandle &sdfSubgridResolution,
        const HdFloatDataSourceHandle &sdfTriangleCountReductionFactor
)
{
    TfToken _names[7];
    HdDataSourceBaseHandle _values[7];

    size_t _count = 0;

    if (sdfBitsPerSubgridPixel) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfBitsPerSubgridPixel;
        _values[_count++] = sdfBitsPerSubgridPixel;
    }

    if (sdfEnableRemeshing) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfEnableRemeshing;
        _values[_count++] = sdfEnableRemeshing;
    }

    if (sdfMargin) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfMargin;
        _values[_count++] = sdfMargin;
    }

    if (sdfNarrowBandThickness) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfNarrowBandThickness;
        _values[_count++] = sdfNarrowBandThickness;
    }

    if (sdfResolution) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfResolution;
        _values[_count++] = sdfResolution;
    }

    if (sdfSubgridResolution) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfSubgridResolution;
        _values[_count++] = sdfSubgridResolution;
    }

    if (sdfTriangleCountReductionFactor) {
        _names[_count] = UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfTriangleCountReductionFactor;
        _values[_count++] = sdfTriangleCountReductionFactor;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfBitsPerSubgridPixel(
    const HdTokenDataSourceHandle &sdfBitsPerSubgridPixel)
{
    _sdfBitsPerSubgridPixel = sdfBitsPerSubgridPixel;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfEnableRemeshing(
    const HdBoolDataSourceHandle &sdfEnableRemeshing)
{
    _sdfEnableRemeshing = sdfEnableRemeshing;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfMargin(
    const HdFloatDataSourceHandle &sdfMargin)
{
    _sdfMargin = sdfMargin;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfNarrowBandThickness(
    const HdFloatDataSourceHandle &sdfNarrowBandThickness)
{
    _sdfNarrowBandThickness = sdfNarrowBandThickness;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfResolution(
    const HdIntDataSourceHandle &sdfResolution)
{
    _sdfResolution = sdfResolution;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfSubgridResolution(
    const HdIntDataSourceHandle &sdfSubgridResolution)
{
    _sdfSubgridResolution = sdfSubgridResolution;
    return *this;
}

UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::SetSdfTriangleCountReductionFactor(
    const HdFloatDataSourceHandle &sdfTriangleCountReductionFactor)
{
    _sdfTriangleCountReductionFactor = sdfTriangleCountReductionFactor;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxSDFMeshCollisionSchema::BuildRetained(
        _sdfBitsPerSubgridPixel,
        _sdfEnableRemeshing,
        _sdfMargin,
        _sdfNarrowBandThickness,
        _sdfResolution,
        _sdfSubgridResolution,
        _sdfTriangleCountReductionFactor
    );
}

/*static*/
UsdPhysicsImagingPhysxSDFMeshCollisionSchema
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxSDFMeshCollisionSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->physxSDFMeshCollision))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->physxSDFMeshCollision;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfBitsPerSubgridPixelLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfBitsPerSubgridPixel);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfEnableRemeshingLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfEnableRemeshing);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfMarginLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfMargin);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfNarrowBandThicknessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfNarrowBandThickness);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfResolutionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfResolution);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfSubgridResolutionLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfSubgridResolution);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxSDFMeshCollisionSchema::GetSdfTriangleCountReductionFactorLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxSDFMeshCollisionSchemaTokens->sdfTriangleCountReductionFactor);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE