//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxConvexHullCollisionSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_CONVEX_HULL_COLLISION_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdIntDataSourceHandle
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetHullVertexLimit() const
{
    return _GetTypedDataSource<HdIntDataSource>(
        UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->hullVertexLimit);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetMinThickness() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->minThickness);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxConvexHullCollisionSchema::BuildRetained(
        const HdIntDataSourceHandle &hullVertexLimit,
        const HdFloatDataSourceHandle &minThickness
)
{
    TfToken _names[2];
    HdDataSourceBaseHandle _values[2];

    size_t _count = 0;

    if (hullVertexLimit) {
        _names[_count] = UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->hullVertexLimit;
        _values[_count++] = hullVertexLimit;
    }

    if (minThickness) {
        _names[_count] = UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->minThickness;
        _values[_count++] = minThickness;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxConvexHullCollisionSchema::Builder &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::Builder::SetHullVertexLimit(
    const HdIntDataSourceHandle &hullVertexLimit)
{
    _hullVertexLimit = hullVertexLimit;
    return *this;
}

UsdPhysicsImagingPhysxConvexHullCollisionSchema::Builder &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::Builder::SetMinThickness(
    const HdFloatDataSourceHandle &minThickness)
{
    _minThickness = minThickness;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxConvexHullCollisionSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxConvexHullCollisionSchema::BuildRetained(
        _hullVertexLimit,
        _minThickness
    );
}

/*static*/
UsdPhysicsImagingPhysxConvexHullCollisionSchema
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxConvexHullCollisionSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->physxConvexHullCollision))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->physxConvexHullCollision;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetHullVertexLimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->hullVertexLimit);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxConvexHullCollisionSchema::GetMinThicknessLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxConvexHullCollisionSchemaTokens->minThickness);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE