//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxCameraSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxCameraSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_CAMERA_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdBoolDataSourceHandle
UsdPhysicsImagingPhysxCameraSchema::GetAlwaysUpdateEnabled() const
{
    return _GetTypedDataSource<HdBoolDataSource>(
        UsdPhysicsImagingPhysxCameraSchemaTokens->alwaysUpdateEnabled);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCameraSchema::BuildRetained(
        const HdBoolDataSourceHandle &alwaysUpdateEnabled
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (alwaysUpdateEnabled) {
        _names[_count] = UsdPhysicsImagingPhysxCameraSchemaTokens->alwaysUpdateEnabled;
        _values[_count++] = alwaysUpdateEnabled;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxCameraSchema::Builder &
UsdPhysicsImagingPhysxCameraSchema::Builder::SetAlwaysUpdateEnabled(
    const HdBoolDataSourceHandle &alwaysUpdateEnabled)
{
    _alwaysUpdateEnabled = alwaysUpdateEnabled;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxCameraSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxCameraSchema::BuildRetained(
        _alwaysUpdateEnabled
    );
}

/*static*/
UsdPhysicsImagingPhysxCameraSchema
UsdPhysicsImagingPhysxCameraSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxCameraSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxCameraSchemaTokens->physxCamera))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxCameraSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxCameraSchemaTokens->physxCamera;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxCameraSchema::GetAlwaysUpdateEnabledLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxCameraSchemaTokens->alwaysUpdateEnabled);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE