//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxVehicleClutchSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxVehicleClutchSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_VEHICLE_CLUTCH_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxVehicleClutchSchema::GetStrength() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxVehicleClutchSchemaTokens->strength);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxVehicleClutchSchema::BuildRetained(
        const HdFloatDataSourceHandle &strength
)
{
    TfToken _names[1];
    HdDataSourceBaseHandle _values[1];

    size_t _count = 0;

    if (strength) {
        _names[_count] = UsdPhysicsImagingPhysxVehicleClutchSchemaTokens->strength;
        _values[_count++] = strength;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxVehicleClutchSchema::Builder &
UsdPhysicsImagingPhysxVehicleClutchSchema::Builder::SetStrength(
    const HdFloatDataSourceHandle &strength)
{
    _strength = strength;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxVehicleClutchSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxVehicleClutchSchema::BuildRetained(
        _strength
    );
}

/*static*/
UsdPhysicsImagingPhysxVehicleClutchSchema
UsdPhysicsImagingPhysxVehicleClutchSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxVehicleClutchSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxVehicleClutchSchemaTokens->physxVehicleClutch))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxVehicleClutchSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxVehicleClutchSchemaTokens->physxVehicleClutch;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleClutchSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleClutchSchema::GetStrengthLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxVehicleClutchSchemaTokens->strength);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE