//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#ifndef PXR_USD_IMAGING_USD_PHYSICS_IMAGING_PHYSX_FORCE_SCHEMA_H
#define PXR_USD_IMAGING_USD_PHYSICS_IMAGING_PHYSX_FORCE_SCHEMA_H

/// \file

#include "pxr/usdImaging/usdPhysicsImaging/api.h"

#include "pxr/imaging/hd/schema.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

// --(BEGIN CUSTOM CODE: Declares)--
// --(END CUSTOM CODE: Declares)--

#define USD_PHYSICS_IMAGING_PHYSX_FORCE_SCHEMA_TOKENS \
    (physxForce) \
    (force) \
    (forceEnabled) \
    (mode) \
    (torque) \
    (worldFrameEnabled) \

TF_DECLARE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxForceSchemaTokens, USDPHYSICSIMAGING_API,
    USD_PHYSICS_IMAGING_PHYSX_FORCE_SCHEMA_TOKENS);

//-----------------------------------------------------------------------------


class UsdPhysicsImagingPhysxForceSchema : public HdSchema
{
public:
    /// \name Schema retrieval
    /// @{

    UsdPhysicsImagingPhysxForceSchema(HdContainerDataSourceHandle container)
      : HdSchema(container) {}

    /// Retrieves a container data source with the schema's default name token
    /// "physxForce" from the parent container and constructs a
    /// UsdPhysicsImagingPhysxForceSchema instance.
    /// Because the requested container data source may not exist, the result
    /// should be checked with IsDefined() or a bool comparison before use.
    USDPHYSICSIMAGING_API
    static UsdPhysicsImagingPhysxForceSchema GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer);

    /// @}

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

    /// \name Member accessor
    /// @{

    USDPHYSICSIMAGING_API
    HdVec3fDataSourceHandle GetForce() const;

    USDPHYSICSIMAGING_API
    HdBoolDataSourceHandle GetForceEnabled() const;

    USDPHYSICSIMAGING_API
    HdTokenDataSourceHandle GetMode() const;

    USDPHYSICSIMAGING_API
    HdVec3fDataSourceHandle GetTorque() const;

    USDPHYSICSIMAGING_API
    HdBoolDataSourceHandle GetWorldFrameEnabled() const; 

    /// @}

    /// \name Schema location
    /// @{

    /// Returns a token where the container representing this schema is found in
    /// a container by default.
    USDPHYSICSIMAGING_API
    static const TfToken &GetSchemaToken();

    /// Returns an HdDataSourceLocator (relative to the prim-level data source)
    /// where the container representing this schema is found by default.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetDefaultLocator();

    /// @}

    /// \name Data source locators for members
    ///
    /// The following methods return an HdDataSourceLocator (relative to the
    /// prim-level data source) where the data source for a member can be found.
    ///
    /// This is often useful for checking intersection against the
    /// HdDataSourceLocatorSet sent with HdDataSourceObserver::PrimsDirtied.
    /// @{

    /// Prim-level relative data source locator to locate force.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetForceLocator();

    /// Prim-level relative data source locator to locate forceEnabled.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetForceEnabledLocator();

    /// Prim-level relative data source locator to locate mode.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetModeLocator();

    /// Prim-level relative data source locator to locate torque.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetTorqueLocator();

    /// Prim-level relative data source locator to locate worldFrameEnabled.
    USDPHYSICSIMAGING_API
    static const HdDataSourceLocator &GetWorldFrameEnabledLocator();
    /// @} 

    /// \name Schema construction
    /// @{

    /// \deprecated Use Builder instead.
    ///
    /// Builds a container data source which includes the provided child data
    /// sources. Parameters with nullptr values are excluded. This is a
    /// low-level interface. For cases in which it's desired to define
    /// the container with a sparse set of child fields, the Builder class
    /// is often more convenient and readable.
    USDPHYSICSIMAGING_API
    static HdContainerDataSourceHandle
    BuildRetained(
        const HdVec3fDataSourceHandle &force,
        const HdBoolDataSourceHandle &forceEnabled,
        const HdTokenDataSourceHandle &mode,
        const HdVec3fDataSourceHandle &torque,
        const HdBoolDataSourceHandle &worldFrameEnabled
    );

    /// \class UsdPhysicsImagingPhysxForceSchema::Builder
    /// 
    /// Utility class for setting sparse sets of child data source fields to be
    /// filled as arguments into BuildRetained. Because all setter methods
    /// return a reference to the instance, this can be used in the "builder
    /// pattern" form.
    class Builder
    {
    public:
        USDPHYSICSIMAGING_API
        Builder &SetForce(
            const HdVec3fDataSourceHandle &force);
        USDPHYSICSIMAGING_API
        Builder &SetForceEnabled(
            const HdBoolDataSourceHandle &forceEnabled);
        USDPHYSICSIMAGING_API
        Builder &SetMode(
            const HdTokenDataSourceHandle &mode);
        USDPHYSICSIMAGING_API
        Builder &SetTorque(
            const HdVec3fDataSourceHandle &torque);
        USDPHYSICSIMAGING_API
        Builder &SetWorldFrameEnabled(
            const HdBoolDataSourceHandle &worldFrameEnabled);

        /// Returns a container data source containing the members set thus far.
        USDPHYSICSIMAGING_API
        HdContainerDataSourceHandle Build();

    private:
        HdVec3fDataSourceHandle _force;
        HdBoolDataSourceHandle _forceEnabled;
        HdTokenDataSourceHandle _mode;
        HdVec3fDataSourceHandle _torque;
        HdBoolDataSourceHandle _worldFrameEnabled;

    };

    /// @}
};

PXR_NAMESPACE_CLOSE_SCOPE

#endif