//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/physxVehicleGearsSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPhysxVehicleGearsSchemaTokens,
    USD_PHYSICS_IMAGING_PHYSX_VEHICLE_GEARS_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdFloatArrayDataSourceHandle
UsdPhysicsImagingPhysxVehicleGearsSchema::GetRatios() const
{
    return _GetTypedDataSource<HdFloatArrayDataSource>(
        UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratios);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxVehicleGearsSchema::GetRatioScale() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratioScale);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPhysxVehicleGearsSchema::GetSwitchTime() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->switchTime);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPhysxVehicleGearsSchema::BuildRetained(
        const HdFloatArrayDataSourceHandle &ratios,
        const HdFloatDataSourceHandle &ratioScale,
        const HdFloatDataSourceHandle &switchTime
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (ratios) {
        _names[_count] = UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratios;
        _values[_count++] = ratios;
    }

    if (ratioScale) {
        _names[_count] = UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratioScale;
        _values[_count++] = ratioScale;
    }

    if (switchTime) {
        _names[_count] = UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->switchTime;
        _values[_count++] = switchTime;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPhysxVehicleGearsSchema::Builder &
UsdPhysicsImagingPhysxVehicleGearsSchema::Builder::SetRatios(
    const HdFloatArrayDataSourceHandle &ratios)
{
    _ratios = ratios;
    return *this;
}

UsdPhysicsImagingPhysxVehicleGearsSchema::Builder &
UsdPhysicsImagingPhysxVehicleGearsSchema::Builder::SetRatioScale(
    const HdFloatDataSourceHandle &ratioScale)
{
    _ratioScale = ratioScale;
    return *this;
}

UsdPhysicsImagingPhysxVehicleGearsSchema::Builder &
UsdPhysicsImagingPhysxVehicleGearsSchema::Builder::SetSwitchTime(
    const HdFloatDataSourceHandle &switchTime)
{
    _switchTime = switchTime;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPhysxVehicleGearsSchema::Builder::Build()
{
    return UsdPhysicsImagingPhysxVehicleGearsSchema::BuildRetained(
        _ratios,
        _ratioScale,
        _switchTime
    );
}

/*static*/
UsdPhysicsImagingPhysxVehicleGearsSchema
UsdPhysicsImagingPhysxVehicleGearsSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPhysxVehicleGearsSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->physxVehicleGears))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPhysxVehicleGearsSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->physxVehicleGears;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleGearsSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleGearsSchema::GetRatiosLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratios);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleGearsSchema::GetRatioScaleLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->ratioScale);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPhysxVehicleGearsSchema::GetSwitchTimeLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPhysxVehicleGearsSchemaTokens->switchTime);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE