//
// Copyright 2023 Pixar
//
// Licensed under the terms set forth in the LICENSE.txt file available at
// https://openusd.org/license.
//
////////////////////////////////////////////////////////////////////////

/* ************************************************************************** */
/* **                                                                      ** */
/* ** This file is generated by a script.                                  ** */
/* **                                                                      ** */
/* ** Do not edit it directly (unless it is within a CUSTOM CODE section)! ** */
/* ** Edit hdSchemaDefs.py instead to make changes.                        ** */
/* **                                                                      ** */
/* ************************************************************************** */

#include "pxr/usdImaging/usdPhysicsImaging/prismaticJointSchema.h"

#include "pxr/imaging/hd/retainedDataSource.h"

#include "pxr/base/trace/trace.h"

// --(BEGIN CUSTOM CODE: Includes)--
// --(END CUSTOM CODE: Includes)--

PXR_NAMESPACE_OPEN_SCOPE

TF_DEFINE_PUBLIC_TOKENS(UsdPhysicsImagingPrismaticJointSchemaTokens,
    USD_PHYSICS_IMAGING_PRISMATIC_JOINT_SCHEMA_TOKENS);

// --(BEGIN CUSTOM CODE: Schema Methods)--
// --(END CUSTOM CODE: Schema Methods)--

HdTokenDataSourceHandle
UsdPhysicsImagingPrismaticJointSchema::GetAxis() const
{
    return _GetTypedDataSource<HdTokenDataSource>(
        UsdPhysicsImagingPrismaticJointSchemaTokens->axis);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPrismaticJointSchema::GetLowerLimit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPrismaticJointSchemaTokens->lowerLimit);
}

HdFloatDataSourceHandle
UsdPhysicsImagingPrismaticJointSchema::GetUpperLimit() const
{
    return _GetTypedDataSource<HdFloatDataSource>(
        UsdPhysicsImagingPrismaticJointSchemaTokens->upperLimit);
}

/*static*/
HdContainerDataSourceHandle
UsdPhysicsImagingPrismaticJointSchema::BuildRetained(
        const HdTokenDataSourceHandle &axis,
        const HdFloatDataSourceHandle &lowerLimit,
        const HdFloatDataSourceHandle &upperLimit
)
{
    TfToken _names[3];
    HdDataSourceBaseHandle _values[3];

    size_t _count = 0;

    if (axis) {
        _names[_count] = UsdPhysicsImagingPrismaticJointSchemaTokens->axis;
        _values[_count++] = axis;
    }

    if (lowerLimit) {
        _names[_count] = UsdPhysicsImagingPrismaticJointSchemaTokens->lowerLimit;
        _values[_count++] = lowerLimit;
    }

    if (upperLimit) {
        _names[_count] = UsdPhysicsImagingPrismaticJointSchemaTokens->upperLimit;
        _values[_count++] = upperLimit;
    }
    return HdRetainedContainerDataSource::New(_count, _names, _values);
}

UsdPhysicsImagingPrismaticJointSchema::Builder &
UsdPhysicsImagingPrismaticJointSchema::Builder::SetAxis(
    const HdTokenDataSourceHandle &axis)
{
    _axis = axis;
    return *this;
}

UsdPhysicsImagingPrismaticJointSchema::Builder &
UsdPhysicsImagingPrismaticJointSchema::Builder::SetLowerLimit(
    const HdFloatDataSourceHandle &lowerLimit)
{
    _lowerLimit = lowerLimit;
    return *this;
}

UsdPhysicsImagingPrismaticJointSchema::Builder &
UsdPhysicsImagingPrismaticJointSchema::Builder::SetUpperLimit(
    const HdFloatDataSourceHandle &upperLimit)
{
    _upperLimit = upperLimit;
    return *this;
}

HdContainerDataSourceHandle
UsdPhysicsImagingPrismaticJointSchema::Builder::Build()
{
    return UsdPhysicsImagingPrismaticJointSchema::BuildRetained(
        _axis,
        _lowerLimit,
        _upperLimit
    );
}

/*static*/
UsdPhysicsImagingPrismaticJointSchema
UsdPhysicsImagingPrismaticJointSchema::GetFromParent(
        const HdContainerDataSourceHandle &fromParentContainer)
{
    return UsdPhysicsImagingPrismaticJointSchema(
        fromParentContainer
        ? HdContainerDataSource::Cast(fromParentContainer->Get(
                UsdPhysicsImagingPrismaticJointSchemaTokens->prismaticJoint))
        : nullptr);
}

/*static*/
const TfToken &
UsdPhysicsImagingPrismaticJointSchema::GetSchemaToken()
{
    return UsdPhysicsImagingPrismaticJointSchemaTokens->prismaticJoint;
}

/*static*/
const HdDataSourceLocator &
UsdPhysicsImagingPrismaticJointSchema::GetDefaultLocator()
{
    static const HdDataSourceLocator locator(GetSchemaToken());
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPrismaticJointSchema::GetAxisLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPrismaticJointSchemaTokens->axis);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPrismaticJointSchema::GetLowerLimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPrismaticJointSchemaTokens->lowerLimit);
    return locator;
}

/* static */
const HdDataSourceLocator &
UsdPhysicsImagingPrismaticJointSchema::GetUpperLimitLocator()
{
    static const HdDataSourceLocator locator =
        GetDefaultLocator().Append(
            UsdPhysicsImagingPrismaticJointSchemaTokens->upperLimit);
    return locator;
} 

PXR_NAMESPACE_CLOSE_SCOPE